<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('Codexmind') ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/imgages/favicon/favicon.ico'))
                        ->prependStylesheet($this->basePath() . '/css/admin/style/style.css')
                        ->prependStylesheet($this->basePath() . '/css/admin/bootstrap-theme.min.css')
                        ->prependStylesheet($this->basePath() . '/css/admin/assets/jquery-ui.css')
                        ->prependStylesheet($this->basePath() . '/css/admin/bootstrap/css/bootstrap.min.css')
                        ->prependStylesheet($this->basePath() . '/css/admin/bootstrap/css/bootstrap-responsive.min.css')
                        ->prependStylesheet($this->basePath() . '/css/admin/vendors/easypiechart/jquery.easy-pie-chart.css')
                        ->prependStylesheet($this->basePath() . '/css/admin/assets/styles.css')
                        ->prependStylesheet($this->basePath() . '/css/admin/css/prettify.css')
                      
        ?>
        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath() . '/js/bootstrap.min.js')
            ->prependFile($this->basePath() . '/js/jquery.form.js')
            //->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
            //->prependFile($this->basePath() . '/js/html5shiv.js',   'text/javascript', array('conditional' => 'lt IE 9',))
           ->prependFile($this->basePath() . '/js/admin/js/jquery-1.7.2.js')

        ; ?>
        

  
 
  
    </head>
    <body>
        <div class="navbar navbar-fixed-top">
            <div class="navbar-inner">
                <div class="container-fluid">
                    <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse"> <span class="icon-bar"></span>
                     <span class="icon-bar"></span>
                     <span class="icon-bar"></span>
                    </a>
                    <a class="brand" href="#">Administration Panel</a>
                    <div class="nav-collapse collapse">
                        <ul class="nav pull-right">
                            <li class="dropdown">
                                <a href="#" role="button" class="dropdown-toggle" data-toggle="dropdown"> <i class="icon-user"></i><?php echo $_SESSION['username'];?><i class="caret"></i>

                                </a>
                                <ul class="dropdown-menu">
                                   <!-- <li class="divider"></li> -->
                                    <li>
                                        <a tabindex="-1" href="/superAdmin/superAdminLogout">Logout</a>
                                    </li>
                                </ul>
                            </li>
                        </ul>
                        <ul class="nav">
                            <li class="active">
                                <a href="#">Dashboard</a>
                            </li>
                            <li class="dropdown">
                                <a href="#" data-toggle="dropdown" class="dropdown-toggle">Employer<b class="caret"></b>

                                </a>
                                <ul class="dropdown-menu" id="menu1">
                                    <li>
                                        <a href="/superAdmin/registration">Employee Profiles</a>
                                    </li>
                                    <li class="divider"></li> 
                                    <li>
                                        <a href="/superAdmin/leave">Company Leave Management</a>
                                    </li>
                                    <li class="divider"></li>  
                                    <li>
                                        <a href="/superAdmin/attendence">Employee Leave Management</a>
                                    </li>
                                    <li class="divider"></li>  
                                    <li>
                                        <a href="/superAdmin/mealPolicy">Meal Policy</a>
                                    </li>
                                    <li class="divider"></li>
                                    <li>
                                         <a href="/superAdmin/upload">Upload CSV File</a>
                                    </li>
                                    
                                                                                  
                                </ul>
                            </li>
                            
                             <li class="dropdown">
                                <a href="#" data-toggle="dropdown" class="dropdown-toggle">Report Generation<b class="caret"></b>

                                </a>
                                <ul class="dropdown-menu" id="menu1">
                                    
                                    <li>
                                        <a href="/superAdmin/userReports">Reports</a>
                                    </li>
                                    <li class="divider"></li>     
                                    <li>
                                        <a href="/superAdmin/userReports/allEmpCharts">All Employees Work Chart</a>
                                    </li>
                                    <li class="divider"></li>     
                                    <li>
                                        <a href="/superAdmin/userReports/employeesMonthWaysChart">Employee Month Ways Chart</a>
                                    </li>
                                     <li class="divider"></li>     
                                    <li>
                                        <a href="/superAdmin/userReports/monthAllChart">Employees Month Ways Working Chart</a>
                                    </li>
                                     <li class="divider"></li>     
                                    <li>
                                        <a href="/superAdmin/userReports/penaltyList">Employees Penalty Management</a>
                                    </li>
                                                                                  
                                </ul>
                            </li>
                            <li class="dropdown">
                                <a href="#" data-toggle="dropdown" class="dropdown-toggle">Salary<b class="caret"></b>

                                </a>
                                <ul class="dropdown-menu" id="menu1">
                                    
                                    <li>
                                        <a href="/superAdmin/userReports/incentive">Employees Salary</a>
                                    </li>
                                    <li class="divider"></li>     
                                    
                                                                                  
                                </ul>
                            </li>
                                                         
                               
                            <li class="dropdown">
                                <a href="#" data-toggle="dropdown" class="dropdown-toggle">Settings <b class="caret"></b>

                                </a>
                                <ul class="dropdown-menu" id="menu1">
                                    
                                    <li>
                                         <a href="/superAdmin/user">User Settings</a>
                                    </li>  
                                     <li class="divider"></li> 
                                     <li>
                                         <a href="/superAdmin/skill">Skill List</a>
                                    </li>  
                                </ul>
                            </li>


                        </ul>
                    </div>
                    <!--/.nav-collapse -->
                </div>
            </div>
        </div>
        <div class="container-fluid">
            <div class="row-fluid">
                
        <div class="container1">
            <?php echo $this->content; ?>
        </div>
            <hr>
            <footer>
                <p>&copy; 2005 - <?php echo date('Y') ?> by Codexmind Technologies Ltd. <?php echo $this->translate('All rights reserved.') ?></p>
            </footer>
        <?php /*</divasd<!-- /container -->*/?>
        <?php echo $this->inlineScript() ?>
    </body>
</html>

