<script src="/js/jquery.maskedinput.js" type="text/javascript"></script>
<script type="text/javascript">
    $(document).ready(function()
    {    
        jQuery(function($){
            $("#date1").mask("99/99/9999");
            $("#date2").mask("99/99/9999");

            $("#date1").change(function(){
                var date= $("#date1").val();
                var dates= date.split("/");

                if(dates[1] > 13)
                {
                    alert("Please enter Correct month");
                    $("#date1").val('');
                }
                if(dates[0] > 32)
                {
                    alert("please enter correct date");
                    $("#date1").val('');
                }
            });
            $("#date2").change(function(){
                var date= $("#date2").val();
                var dates= date.split("/");

                if(dates[1] > 13)
                {
                    alert("Please enter Correct month");
                    $("#date2").val('');
                }
                if(dates[0] > 32)
                {
                    alert("please enter correct date");
                     $("#date2").val('');
                }
            });
            
            $("#date1").change(function(){
                
               var d1= $("#date1").val();
               $("#hid1").val(d1);
               
            });
            
            $("#date2").click(function(){
                
                var hidden= $('#hid1').val();
                if(hidden == 0)
                {
                    alert("Please Enter From date");
                    $('#date1').focus();
                }              
            });
            
            $("#date2").change(function(){
                
                var d2= $('#date2').val();
                if(d2 == 0)
                {
                    alert("Please Enter To date");
                }    
               
            });

        });
    });
</script>


<div class="span99" id="content">
    <div class="row-fluid">
      	<div class="navbar">
           	
        </div>
    </div>
    <div class="row-fluid">
        <div class="span12">
            
            <div class="block">
                <div class="navbar navbar-inner block-header">
                    <div class="muted pull-left" style="text-align:center; float: left; width:100%;">All Employee Working Hours Listings<div id="msg" style="font-size:12px; color:red; text-align:center;">
                        <?php
                            if(count($flashMessages))
                            {
                                foreach ($flashMessages as $msg)
                                {
                                    echo $msg.'</blink><br>';   
                                }   
                            }
                        ?>
                    </div>
                        
                        <div class="muted pull-left" style="width: 1266px; background-color: #FFFFCC;">
                            <div style="margin: 0 auto; padding: 0px; color: #FFCC00;">Date Wise Record</div>
                            <form id="detailsForm" name="detailsForm" method="post" action="/superAdmin/userReports/ajaxCharts">
                                <input type="text" name="date1" id="date1" placeholder="DD/MM/YYYY">
                                <input type="text" name="date2" id="date2" placeholder="DD/MM/YYYY">
                                <input type="submit" name="submit" class="btn btn-primary" style="margin-bottom: 13px;">
                                <input type="hidden" name="hid1" id="hid1"> 
                            </form>
                        </div>
                        
                    </div>
                </div>
            </div>
        </div>