<script type="text/javascript">
    $(document).ready(function()
    {
        $("#name").change(function()
        {
            var name= $("#name").val();
            $("#nme").val(name);
            
        });
        $("#mnth").change(function(){
            var month= $("#mnth").val();
            var name= $("#nme").val();
            $("#mnt").val(month);
            if(name == '')
            {
                alert("Please select a User");
                $("#mnth").val('');
                $( "#name" ).focus();
            }
                        
        });
        $("#year").change(function(){
            var month= $("#mnt").val();
            var name= $("#nme").val();
            var year= $("#year").val();
            $("#mnt").val(month);
            if(name == '')
            {
                alert("Please select a User");
                $("#year").val('');
                $( "#name" ).focus();
            }
            if(month == '')
            {
                alert("Please select a Month");
                $("#year").val('');
                $( "#mnth" ).focus();
            }
//            $.ajax({
//                type    :   "POST",
//                url     :   "/superAdmin/userReports/incentiveSalary",
//                cache   :   false,
//                data    :   { name:name, month: month, year:year},
//                dataType:   "html",
//                success :   function()
//                {
//                    alert("haiiii");
//                },
//                error   :   function()
//                {
//                    
//                },
//            });
                        
        });
        var $i=1;
        $("#plus").click(function(){
            var s= $i++;
            $.ajax({
                type    :   "POST",
                url     :   "/superAdmin/userReports/bankTable",
                cache   :   false,
                data    :   {cnt:s}, 
                dataType    :   "html",
                success :   function(data)
                {
                    $("#ajx_table").append(data);
                },
                error   :   function()
                {
                    alert("error");
                },
                
            });
        });
        
        var $j=1;
        $("#incen").click(function(){
            var cn= $j++;
            $.ajax({
                type    :   "POST",
                url     :   "/superAdmin/userReports/incentiveTable",
                cache   :   false,
                data    :   {cnt:cn}, 
                dataType    :   "html",
                success :   function(data)
                {
                    $("#ajx_table_inc").append(data);
                },
                error   :   function()
                {
                    alert("error");
                },
                
            });
        });
        
        $(".cls").live('click',function()
        {
            var id= $(this).attr('id');
            var delId= id.split('_');
            $("#cp"+delId[1]).remove();
        });
        $(".clsIn").live('click',function()
        {
            var id= $(this).attr('id');
            var delId= id.split('_');
            $("#cpIn"+delId[1]).hide();
        });
       
        $("#advPayback").change(function(){
            var val=$("#advPayback").val();
            var actSal=$('#salHid').val();
            
            $('#salHid').val(actSal-val);
            $('#sal').val(actSal-val);

            var hourSal=$('#hourSalHid').val();
            $('#hourSalHid').val(hourSal-val);
            $('#hourSal').val(hourSal-val);

            var dayBaseSal=$('#dayBaseSal').val();
            $('#dayBaseSalHid').val(dayBaseSal-val);
            $('#dayBaseSal').val(dayBaseSal-val);
           
        });
        $("#loanPayback").change(function(){
            var val=$("#loanPayback").val();
            var actSal=$('#salHid').val();
            
            $('#salHid').val(actSal-val);
            $('#sal').val(actSal-val);

            var hourSal=$('#hourSalHid').val();
            $('#hourSalHid').val(hourSal-val);
            $('#hourSal').val(hourSal-val);

            var dayBaseSal=$('#dayBaseSal').val();
            $('#dayBaseSalHid').val(dayBaseSal-val);
            $('#dayBaseSal').val(dayBaseSal-val);
           
        });
        $("#payingSal").change(function(){
            var payingSal= $("#payingSal").val();
            
            var penalty= <?php echo $this->penalty;?>;
            var tot= payingSal-penalty;
            
            $("#paidSal").val(tot);
            
        });
        
    });
    function getPayMoney(mny,pasCnt)
    {
        var mny=mny;
        var pasCnt=pasCnt;
        var actSal=$('#salHid').val();
            
        $('#salHid').val(actSal-mny);
        $('#sal').val(actSal-mny);
         
        var hourSal=$('#hourSalHid').val();
        $('#hourSalHid').val(hourSal-mny);
        $('#hourSal').val(hourSal-mny);
            
        var dayBaseSal=$('#dayBaseSal').val();
        $('#dayBaseSalHid').val(dayBaseSal-mny);
        $('#dayBaseSal').val(dayBaseSal-mny);
            
            
    }
    function getIncentiveMoney(inMny,inPasCnt)
    {
        var inMny=inMny;
        //alert(inMny);    
        var inPasCnt=inPasCnt;
        var curntSal=$('#salHid').val();
        //alert(curntSal);    
        $('#salHid').val(+curntSal + +inMny);
        $('#sal').val(+curntSal + +inMny);
         
        var hourSal=$('#hourSalHid').val();
        $('#hourSalHid').val(+hourSal + +inMny);
        $('#hourSal').val(+hourSal + +inMny);
            
        var dayBaseSal=$('#dayBaseSal').val();
        $('#dayBaseSalHid').val(+dayBaseSal + +inMny);
        $('#dayBaseSal').val(+dayBaseSal + +inMny);
            
            
    }
    
    
</script>
<link href="/css/facebox.css" media="screen" rel="stylesheet" type="text/css" />
  <script src="/js/facebox.js" type="text/javascript"></script>
    <script type="text/javascript">
        jQuery(document).ready(function($) {
            $('a[rel*=facebox]').facebox({
                loadingImage : '/images/loading.gif',
                closeImage   : '/images/closelabel.png'
            })
          })
  </script>
<div class="span99" id="content">
    <div class="row-fluid">
      	<div class="navbar">
           	
        </div>
    </div>
    <div class="row-fluid">
        <div class="span12">
            <div class="block">
                <div class="navbar navbar-inner block-header">
                    <div class="muted pull-left" style="text-align:center; float: left; width:100%;">Incentive Management<div id="msg" style="font-size:12px; color:red; text-align:center;">
                        <?php
                            if(count($flashMessages))
                            {
                                foreach ($flashMessages as $msg)
                                {
                                    echo $msg.'</blink><br>';   
                                }   
                            }
                        ?>
                    </div>

                    
                </div>
                    <div class="block-content collapse in">
                    <form action="/superAdmin/userReports/incentiveSalary" method="post" name="frm1">
                        <table class="table table-striped">
                            <tbody>
                                <tr>
                                    <td>
                                        <input type="hidden" id="nme" name="nme">
                                        <input type="hidden" id="mnt" name="mnt">
                                        <select id="name" name="name" required>
                                            <option value="">Name please</option>
                                            <?php
                                            foreach ($userNames as $value)
                                            {
                                            ?>
                                            <option value="<?php echo $value['employee_code']?>"><?php echo $value['employee_name']?></option>
                                            <?php
                                            }
                                            ?>                                
                                        </select>
                                    </td>
                                    <td>
                                        <select id="mnth" name="mnth" required>
                                            <option value="">Month please</option>
                                            <option value="01">Jan</option>
                                            <option value="02">Feb</option>
                                            <option value="03">March</option>
                                            <option value="04">April</option>
                                            <option value="05">May</option>
                                            <option value="06">June</option>
                                            <option value="07">July</option>
                                            <option value="08">Aug</option>
                                            <option value="09">Sep</option>
                                            <option value="10">Oct</option>
                                            <option value="11">Nov</option>
                                            <option value="12">Dec</option>
                                    </td>
                                    <td>
                                        <select id="year" name="year" required>
                                            <option value="">Year please</option>
                                            <option value="2013">2013</option>
                                            <option value="2014">2014</option>
                                            <option value="2015">2015</option>
                                            <option value="2016">2016</option>
                                            <option value="2017">2017</option>
                                        </select>
                                    </td>
                                    <td>
                                        <input type="submit">
                                    </td>
                                </tr>



                            </tbody>
                        </table>
                    </form>
                </div>
                <div class="block-content collapse in" style="overflow:visible;">
                </div>
                    <?php 
                    if(count($this->salary))
                    {                    
                    ?>
                    <div class="control-group">
                        <table class="table table-striped">
                            <tbody>
                                <tr>
                                    <td>MonthWays</td><td><?php echo $this->salary ;?></td>
                                </tr>
                                <tr>
                                    <td>Hourways</td><td><?php echo $this->hourbaseSalary ;?></td>
                                </tr>
                                <tr>
                                    <td>Day Base</td><td><?php echo $this->daybaseSalary ;?></td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                    <table class="table table-striped">
                        
                        <tr>
                            <td>Advance Payback</td><td><input type="text" name="date1" placeholder="dd/mm/yyyy"></td><td><input type="text" name="advPayback" id="advPayback" placeholder="Advance"></td>
                        </tr>
                        <tr>
                            <td>Loan Payback</td><td><input type="text" name="date2" placeholder="dd/mm/yyyy"></td><td><input type="text" name="loanPayback" id="loanPayback" placeholder="Loan"></td>
                        </tr>
<!--                        <tr>
                            <td>
                                <div class="control-group">
                                    <div id="ajx_table"></div>
                                </div>
                                <div class="control-group" style="float:right">
                                     Bankactivity<img id="plus" border="0" title="Bankactivity" src="/images/plus.png">
                                </div>                                
                            </td>
                        </tr>-->
                        <tr>
                            <td colspan="3">
                                <div class="control-group">
                                    <div id="ajx_table_inc"></div>
                                </div>
                                <div class="control-group" style="float:right">
                                     Incentive<img id="incen" border="0" title="incentive" src="/images/plus.png">
                                </div>
                            </td>
                        </tr>
<!--                        <tr>
                            <td colspan="3">
                                <div class="control-group" style="float:right">
                                    <a href="/superAdmin/userReports/penalty/<?php echo $this->userId; ?>/<?php echo $this->mnth; ?>/<?php echo $this->year; ?>" rel="facebox">Penality</a>
                                </div>
                            </td>
                        </tr>-->
                        <tr>
                            <td colspan="5"  style="text-align: right">
                                <div class="control-group">
                                    <table class="table table-striped" style="text-align: right">
                                        <tbody>
                                            <tr>
                                                <td>MonthWays</td>
                                                <td>
                                                    <input type="text" id="sal" name="sal" value="<?php echo $this->salary?>" readonly>
                                                    <input type="hidden" id="salHid" value="<?php echo $this->salary?>"> 
                                                </td>
                                            </tr>
                                            <tr>
                                                <td>Hourways</td>
                                                <td>
                                                    <input type="text" id="hourSal" name="hourSal" value="<?php echo $this->hourbaseSalary ;?>" readonly>
                                                    <input type="hidden" id="hourSalHid" value="<?php echo $this->hourbaseSalary ;?>">
                                                </td>
                                            </tr>
                                            <tr>
                                                <td>Day Base</td>
                                                <td>
                                                    <input type="text" id="dayBaseSal" name="dayBaseSal" value="<?php echo $this->daybaseSalary ;?>" readonly>
                                                    <input type="hidden" id="dayBaseSalHid" value="<?php echo $this->daybaseSalary;?>">
                                                </td>
                                            </tr>
                                        </tbody>
                                    </table>
                                </div>
                            </td>
                        </tr>
                        <tr>
                            <td colspan="5"  style="text-align: center;">Grand Total</td>                           ;
                        </tr>
                        <tr>
                            <td colspan="2"  style="text-align: center">Penalty</td><td colspan="2" style="text-align: center">
                                <?php echo $this->penalty;?>&nbsp;&nbsp;<a href="/superAdmin/userReports/penaltyPerMonth/<?php echo $this->userId ?>/<?php echo $this->mnth ?>/<?php echo $this->year ?>" rel="facebox">View</a>
                            </td>
                        </tr>
                        <tr>
                            <td colspan="2"  style="text-align: center">Paying Salary</td><td colspan="2" style="text-align: center">
                                <input type="text" id="payingSal" id="payingSal" required="">
                            </td>
                        </tr>
                        <tr>
                            <td colspan="2"  style="text-align: center">Paid Salary</td><td colspan="2" style="text-align: center">
                                <input type="text" id="paidSal" id="paidSal" readonly>
                            </td>
                        </tr>
                        <tr>
                            <td style="text-align: center;" colspan="5">
                                <input type="submit" value="submit" name="submit">
                            </td>
                        </tr>
                    </table>
                    
                    
                    
                    <?php
                    }
                    else
                    {
                    ?>
                        <div class="control-group">
                        <table class="table table-striped">
                            <tbody>
                                <tr>
                                    Oops no record found .....
                                </tr>
                            </tbody>
                        </table>
                    </div>
                    
                    <?php    
                    }
                    ?>
                    
            </div>
        </div>
    </div>