<script src="/js/jquery.maskedinput.js" type="text/javascript"></script>
<script type="text/javascript">
    $(document).ready(function()
    {    
        jQuery(function($){
            $("#date1").mask("99/99/9999");
            $("#date2").mask("99/99/9999");

            $("#date1").change(function(){
                var date= $("#date1").val();
                var dates= date.split("/");

                if(dates[1] > 13)
                {
                    alert("Please enter Correct month");
                    $("#date1").val('');
                }
                if(dates[0] > 32)
                {
                    alert("please enter correct date");
                    $("#date1").val('');
                }
            });
            $("#date2").change(function(){
                var date= $("#date2").val();
                var dates= date.split("/");

                if(dates[1] > 13)
                {
                    alert("Please enter Correct month");
                    $("#date2").val('');
                }
                if(dates[0] > 32)
                {
                    alert("please enter correct date");
                     $("#date2").val('');
                }
            });

        });
    });
</script>


<div class="span99" id="content">
    <div class="row-fluid">
      	<div class="navbar">
           	
        </div>
    </div>
    <div class="row-fluid">
        <div class="span12">
            
            <div class="block">
                <div class="navbar navbar-inner block-header">
                    <div class="muted pull-left" style="text-align:center; float: left; width:100%;">Employee Records Listings<div id="msg" style="font-size:12px; color:red; text-align:center;">
                        <?php
                            if(count($flashMessages))
                            {
                                foreach ($flashMessages as $msg)
                                {
                                    echo $msg.'</blink><br>';   
                                }   
                            }
                        ?>
                    </div>
                        
                        <div class="muted pull-left" style="width: 1266px; background-color: #FFFFCC;">
                            <div style="margin: 0 auto; padding: 0px; color: #FFCC00;">Date Wise Record</div>
                        <form id="detailsForm" name="detailsForm" method="post" action="<?php echo $this->path ?>/superAdmin/userReports/userReports">
                            <select id="name" name="name" required>
                                <option value="">Name please</option>
                                <?php
                                foreach ($userNames as $value)
                                {
                                ?>
                                <option value="<?php echo $value['employee_code']?>"><?php echo $value['employee_name']?></option>
                                <?php
                                }
                                ?>
                                
                            </select>
                            <input type="text" name="date1" id="date1">
                            <input type="text" name="date2" id="date2">
                            <input type="submit" name="submit" value="Submit" style="margin-bottom: 11px; padding: 3px; width: 99px;">
                        </form>
                    </div>

                    
                </div>
                <div class="block-content collapse in">
                    <table class="table table-striped">
                        <thead>
                            <tr>
                                <th style="text-align:center;">Date</th>
                                <th style="text-align:center;">In Time</th>
                                <th style="text-align:center;">Out Time</th>
                                <th style="text-align:center;">Working Hour</th>
                                <th style="text-align:center;">OT</th>
                                <th style="text-align:center;">Total Work</th>
                                <th style="text-align:center;">Under Time</th>
                                <th style="text-align:center;">Early By</th>
                                <th style="text-align:center;">Late By</th>
                            </tr>
                            <?php
                            if(count($records) != '')
                            {
                                foreach ($records as $value)
                                {
                                ?>
                                <tr>
                                    <td style="text-align:center;"><?php echo $value['worked_date']; ?></td>
                                    <td style="text-align:center;">
                                        <?php
                                            echo date('h:i A', strtotime($value['in_time']));
                                        ?>
                                    </td>
                                    <td style="text-align:center;">
                                        <?php
                                            echo date('h:i A', strtotime($value['out_time']));
                                        ?>
                                    </td>
                                    <td style="text-align:center;">
                                        <?php
                                            $s= split(':',$value['worked_hour']);
                                            echo $s[0].':'.$s[1];
                                        ?>
                                    </td>
                                    <td style="text-align:center;">
                                        <?php
                                        if($value['over_time'] != '00:00:00')
                                        {
                                            $s= split(':',$value['over_time']);
                                            echo $s[0].':'.$s[1];
                                        }
                                        else
                                        {
                                            echo "-";
                                        }
                                        ?>
                                    </td>
                                    <td style="text-align:center;">
                                        <?php
                                            $s1= split(':',gmdate("H:i:s", abs(strtotime($value['worked_hour'])+ strtotime($value['over_time']))));
                                            if(gmdate("H:i:s", abs(strtotime($value['worked_hour'])+ strtotime($value['over_time']))) < '08:00:00')
                                            {
                                                echo "correct".$s1[0].':'.$s[1];
                                            }
                                            else 
                                            {
                                                echo "not correct".$s1[0].':'.$s[1];   
                                            }
                                            
                                        ?>
                                    </td>
                                    <td style="text-align:center;">
                                        <?php
                                        if($value['under_time'] != '00:00:00')
                                        {
                                            $s= split(':',$value['under_time']);
                                            echo $s[0].':'.$s[1];
                                        }
                                        else
                                        {
                                            echo "-";
                                        }
                                        ?>
                                    </td>
                                    
                                </tr>
                                <?php
                                }
                            }
                            else
                            {
                            ?>
                                <tr>
                                    <td colspan="6" style="text-align:center;">Oops no records founds..</td>
                                </tr>
                            <?php   
                            }
                            ?>
                                
                                
                        </thead>
                    </table>
                </div>
            </div>
        </div>
    </div>
                 
<div id="response"></div>