<script src="/js/jquery.maskedinput.js" type="text/javascript"></script>
<script type="text/javascript">
    $(document).ready(function()
    {    
        jQuery(function($){
            $("#date1").mask("99/99/9999");
            $("#date2").mask("99/99/9999");

            $("#date1").change(function(){
                var date= $("#date1").val();
                var dates= date.split("/");

                if(dates[1] > 13)
                {
                    alert("Please enter Correct month");
                    $("#date1").val('');
                }
                if(dates[0] > 32)
                {
                    alert("please enter correct date");
                    $("#date1").val('');
                }
            });
            $("#date2").change(function(){
                var date= $("#date2").val();
                var dates= date.split("/");

                if(dates[1] > 13)
                {
                    alert("Please enter Correct month");
                    $("#date2").val('');
                }
                if(dates[0] > 32)
                {
                    alert("please enter correct date");
                     $("#date2").val('');
                }
            });

        });
    });
</script>


<div class="span99" id="content">
    <div class="row-fluid">
      	<div class="navbar">
           	
        </div>
    </div>
    <div class="row-fluid">
        <div class="span12">
            
            <div class="block">
                <div class="navbar navbar-inner block-header">
                    <div class="muted pull-left" style="text-align:center; float: left; width:100%;">Employee Records Listings<div id="msg" style="font-size:12px; color:red; text-align:center;">
                        <?php
                            if(count($flashMessages))
                            {
                                foreach ($flashMessages as $msg)
                                {
                                    echo $msg.'</blink><br>';   
                                }   
                            }
                        ?>
                    </div>
                        
                        <div class="muted pull-left" style="width: 1266px; background-color: #FFFFCC;">
                            <div style="margin: 0 auto; padding: 0px; color: #FFCC00;">Date Wise Record</div>
                        <form id="detailsForm" name="detailsForm" method="post" action="/superAdmin/userReports/userReports">
                            <select id="name" name="name" required>
                                <option value="">Name please</option>
                                <?php
                                foreach ($userNames as $value)
                                {
                                ?>
                                <option value="<?php echo $value['employee_code']?>"><?php echo $value['employee_name']?></option>
                                <?php
                                }
                                ?>
                                
                            </select>
                            <input type="text" name="date1" id="date1" placeholder="DD/MM/YYYY">
                            <input type="text" name="date2" id="date2" placeholder="DD/MM/YYYY">
                            <input type="submit" name="submit" value="Submit" style="margin-bottom: 11px; padding: 3px; width: 99px;">
                        </form>
                    </div>

                    
                </div>
                <div class="block-content collapse in">
                    <table class="table table-striped">
                       
                            <tr>
                                <td><?php echo $this->uname ;?></td>
                            </tr>
                            <tr>
                                <td style="text-align:center;">Date</td>
                                <td style="text-align:center;">In Time</td>
                                <td style="text-align:center;">Out Time</td>
                                <td style="text-align:center;">Normal Working</td>
                                <td style="text-align:center;">OT</td>
                                <td style="text-align:center;">Working Hour</td>                                
                               
                                <td style="text-align:center;">Under Time</th>
                                <td style="text-align:center;">Early By</th>
                                <td style="text-align:center;">Late By</th>
                            </tr>
                            <?php
                            $cnt= count($records);
                            if($cnt != '')
                            {
                                foreach ($records as $value)
                                {        
                                    $s=$value['worked_hour'];
                                ?>
                                <tr <?php if($s < '08:00:00'){ ?>style="color:red;" <?php } ?>>
                                    <td style="text-align:center;"><?php echo $value['worked_date']; ?></td>
                                    <td style="text-align:center;">
                                        <?php
                                            echo date('h:i A', strtotime($value['in_time']));
                                        ?>
                                    </td>
                                    <td style="text-align:center;">
                                        <?php
                                        if($value['out_time'] != '00:00:00')
                                        {
                                            echo date('h:i A', strtotime($value['out_time']));
                                        }
                                        else
                                        {
                                            echo date('h:i A', strtotime($this->sout));
                                        }
                                            
                                        ?>
                                    </td>
                                    <td style="text-align:center;">
                                        <?php
                                        $s= split(":",gmdate("H:i:s", abs(strtotime($value['worked_hour'])- strtotime($value['over_time']))));
                                        echo $s[0].':'.$s[1];
                                        ?>
                                    </td>
                                   
                                    <td style="text-align:center;">
                                        <?php
                                        if($value['over_time'] != '00:00:00')
                                        {
                                            $s= split(':',$value['over_time']);
                                            echo $s[0].':'.$s[1];
                                        }
                                        else
                                        {
                                            echo "-";
                                        }
                                        ?>
                                    </td>
                                     <td style="text-align:center;">
                                        <?php
                                        $s1= split(':',$value['worked_hour']);
                                        echo $s1[0].':'.$s1[1];
                                        ?>
                                    </td>
                                    
                                    <td style="text-align:center;">
                                        <?php
                                        if($value['under_time'] != '00:00:00')
                                        {
                                            $s= split(':',$value['under_time']);
                                            echo $s[0].':'.$s[1];
                                        }
                                        else
                                        {
                                            echo "-";
                                        }
                                        ?>
                                    </td>
                                    <td style="text-align:center;">
                                        <?php
                                        if($value['early_by'] != '00:00:00')
                                        {
                                            echo date('H:i', strtotime($value['early_by']));
                                        }
                                        else
                                        {
                                            echo "-";
                                        }
                                        ?>
                                    </td>
                                    <td style="text-align:center;">
                                        <?php
                                        if($value['late_by'] != '00:00:00')
                                        {
                                            echo date('H:i', strtotime($value['late_by']));
                                        }
                                        else
                                        {
                                            echo "-";
                                        }
                                        ?>
                                    </td>
                                    
                                </tr>
                                
                                <?php
                                }
                                ?>
                                <tr>
                                    <td colspan="8">
                                        <div class="muted pull-left" style="width: 1266px; background-color: #FFFFCC; padding: 0px;">
                                            <div style="float:left; width: 580px; padding: 24px;">
                                                <div style="float:left;width: 200px; padding: 0px; font-weight: bold;">Working Hours</div>
                                                <div style="float:left;width: 200px; padding: 0px; font-weight: bold; color: red;"><?php echo $tc= $cnt * 8;?></div>
                                                <br>
                                                <br>
                                                <div style="float:left;width: 200px; padding: 0px; font-weight: bold;">Work Hours(<span style="font-size:10px;">Including OT</span>)</div>                                               
                                                <div style="float:left;width: 200px; padding: 0px; font-weight: bold; color: red;"><?php echo $this->totWork;?></div>
                                                <br>
                                                <br>
                                                <div style="float:left;width: 200px; padding: 0px; font-weight: bold;">Work Difference</div>                                               
                                                <div style="float:left;width: 200px; padding: 0px; font-weight: bold; color: red;">
                                                    <?php
                                                    $s= split(':',$this->totWork);
                                                    //if($this->totWork > $tc)
                                                    //{
                                                        echo $s[0]-$tc.' '.'Hours'; 
                                                   // }
                                                    //elseif($this->totWork < $tc)
                                                    //{
                                                     //   echo $s[0]- $tc; 
                                                    ///}
                                                    //else
                                                    //{
                                                     //   echo $this->totWork;
                                                    //}
                                                    ?>
                                                </div>
                                            </div>
                                            <div style="float:left; width: 580px; padding: 24px;">
                                                <div style="float:left;width: 200px; padding: 0px; font-weight: bold;">Total OT</div>
                                                <div style="float:left;width: 200px; padding: 0px; font-weight: bold; color: red;"><?php echo $this->ot?></div>
                                            </div>
                                            <?php if($this->d1 !== '' && $this->d2){ ?>
                                            <div style="float:left; width: 580px; padding: 24px;">
                                               
                                                <div style="float:left;width: 200px; padding: 0px; font-weight: bold;"><a href="/superAdmin/userReports/charts/<?php echo $this->d1.'_'.$this->d2.'_'.$this->uid;?>">Chart representation</a></div>   
                                            </div>
                                            <?php
                                            }
                                            ?>
                                                                                        
                                        </div>
                                    </td>
                                </tr>
                                <?php
                            }
                            else
                            {
                            ?>
                                <tr>
                                    <td colspan="6" style="text-align:center;">Oops no records founds..</td>
                                </tr>
                            <?php   
                            }
                            ?>
                                
                                
                        
                    </table>
                    
                    
                </div>
            </div>
        </div>
    </div>
                 
<div id="response"></div>