<script src="/js/jquery.maskedinput.js" type="text/javascript"></script>
<script type="text/javascript">
    jQuery(function($){
        var hidId= <?php echo $this->count ;?>;
        $('#penDate'+ hidId).mask("99/99/9999");
                
        $("#penDate"+hidId).change(function(){
            
            var date= $("#penDate"+hidId).val();
            var dates= date.split("/");
            
            if(dates[1] > 13)
            {
                alert("Please enter Correct month");
                $("#penDate"+hidId).val('');
            }
            if(dates[0] > 32)
            {
                alert("please enter correct date");
                $("#penDate"+hidId).val('');
            }
        });
          
    });
    
    
    
</script>
<div id="pen<?php echo $this->count ;?>">
    <table class="table table-striped table-bordered table-hover dataTable no-footer" aria-describedby="dataTables-example_info">
        <tr>
            <td>
                <label class="control-label" for="typeahead">Leave Date</label>
                <select class="form-control" id="name<?php echo $this->count ;?>" name="name[]" required>
                    <option value="">Name please</option>
                    <?php
                    foreach ($userNames as $value)
                    {
                    ?>
                        <option value="<?php echo $value['employee_code']?>"><?php echo $value['employee_name']?></option>
                    <?php
                    }
                    ?>                                
                </select>
            </td>
            <td>
                <label class="control-label" for="typeahead">Date</label>
                <input type="text" name="penDate[]" id="penDate<?php echo $this->count ;?>">
            </td>
            <td>
                <label class="control-label" for="typeahead">Amount</label>
                <input type="text" name="amount[]" id="amount<?php echo $this->count ;?>">
            </td>
            <td style="border-bottom:1px solid #DDDDDD;">
                <label class="control-label" for="textarea2">For What</label>
                <textarea name="dis[]" id="dis<?php echo $this->count ;?>" placeholder="For What"required></textarea>
                <input type="hidden" id="cnt" name="cnt" value="<?php echo $this->count ;?>">
            </td>
            <td>
                <img src="/images/minus.png" border="0" title="delete" id="close_<?php echo $this->count;?>" class="cls" style="margin-top:38px;">
            </td>
        </tr>
    </table>
</div>