<script src="/js/jquery.maskedinput.js" type="text/javascript"></script>
<script type="text/javascript">
    $(document).ready(function()
    {

        var $i=2;
        $("#plus").click(function(){
            var s= $i++;
            $('#cnt').val(s);
            $.ajax({
                type    :   "POST",
                url     :   "/superAdmin/userReports/penaltyTable",
                cache   :   false,
                data    :   {cnt:s}, 
                dataType    :   "html",
                success :   function(data)
                {
                    $("#ajx_table").append(data);
                },
                error   :   function()
                {
                    alert("error");
                },
                
            });
        });
        
        
        $(".cls").live('click',function()
        {
            var id= $(this).attr('id');
            var delId= id.split('_');
            //$("#pen"+delId[1]).hide();
            $("#pen"+delId[1]).remove();
            
        });
                
    });
    jQuery(function($){
        var hidId= $("#cnt").val();
        
        $('#penDate'+ hidId).mask("99/99/9999");
                
        $("#penDate"+hidId).change(function(){
            
            var date= $("#penDate"+hidId).val();
            var dates= date.split("/");
            
            if(dates[1] > 13)
            {
                alert("Please enter Correct month");
                $("#penDate"+hidId).val('');
            }
            if(dates[0] > 32)
            {
                alert("please enter correct date");
                $("#penDate"+hidId).val('');
            }
        });
          
    });
    
    
    
</script>
<link href="/css/facebox.css" media="screen" rel="stylesheet" type="text/css" />
  <script src="/js/facebox.js" type="text/javascript"></script>
    <script type="text/javascript">
        jQuery(document).ready(function($) {
            $('a[rel*=facebox]').facebox({
                loadingImage : '/images/loading.gif',
                closeImage   : '/images/closelabel.png'
            })
          })
  </script>

       
<div class="span9999" id="content">
    <div class="row-fluid">
        <div class="span12">
            <div class="block">
                <div class="navbar navbar-inner block-header">
                    <div class="muted pull-left">Penalty Adding Form</div>
                </div>
                <div class="block-content collapse in">
                    <form class="form-horizontal" id="addProduct" method="post" enctype="multipart/form-data" action="/superAdmin/userReports/addPenalty">
                            <fieldset>
                                <table class="table table-striped table-bordered table-hover dataTable no-footer" aria-describedby="dataTables-example_info">
                                    <tr>
                                        <td>
                                            <label class="control-label" for="typeahead">Leave Date</label>
                                                <select class="form-control" id="name1" name="name[]" required>
                                                        <option value="">Name please</option>
                                                        <?php
                                                        foreach ($userNames as $value)
                                                        {
                                                        ?>
                                                        <option value="<?php echo $value['employee_code']?>"><?php echo $value['employee_name']?></option>
                                                        <?php
                                                        }
                                                        ?>                                
                                                </select>
                                            </td>
                                        <td>
                                            <label class="control-label" for="typeahead">Date</label>
                                            <input type="text" name="penDate[]" id="penDate1">
                                        </td>
                                        <td>
                                            <label class="control-label" for="typeahead">Amount</label>
                                            <input type="text" name="amount[]" id="amount1">
                                        </td>
                                        <td style="border-bottom:1px solid #DDDDDD;">
                                            <label class="control-label" for="textarea2">For What</label>
                                            <textarea name="dis[]" id="dis1" placeholder="For What" required></textarea>
                                            <input type="hidden" id="cnt" name="cnt" value="1">
                                        </td>
<!--                                        <td>
                                            <img src="/images/minus.png" border="0" title="delete" id="close1" class="cls" style="margin-top:38px;">
                                        </td>-->
                                    </tr>
                                    <tr>
                                        <td colspan="5">
                                            <div class="control-group">
                                                <div id="ajx_table"></div>
                                            </div>
                                            <div class="control-group" style="float:right">
                                                 Penalty<img id="plus" border="0" title="More" src="/images/plus.png">
                                            </div>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td colspan="5">                                            
                                            <button type="submit" name="submit" class="btn btn-primary">Save</button>
                                            <button type="reset" class="btn" id="cancel">Cancel</button>
                                        </td>
                                    </tr>                                                     
                                </table>
                                
                            </fieldset>
                        </form>

                    </div>
                </div>
            </div>
            <!-- /block -->


        </div>

    </div>

</div>
</div>
<script type="text/javascript">
    $("#cancel").click(function()
    {
        window.location.href= "<?php echo $this->basePath()?>/superAdmin/userReports/penaltyList";
    });

</script>