<link href="/css/facebox.css" media="screen" rel="stylesheet" type="text/css" />
  <script src="/js/facebox.js" type="text/javascript"></script>
    <script type="text/javascript">
        jQuery(document).ready(function($) {
            $('a[rel*=facebox]').facebox({
                loadingImage : '/images/loading.gif',
                closeImage   : '/images/closelabel.png'
            })
          })
  </script>
<div class="span99" id="content">
    <div class="row-fluid">
      	<div class="navbar">
           	
        </div>
    </div>
    <div class="row-fluid">
        <div class="span12">
            <div style="margin-left:1120px;"><a href="/superAdmin/userReports/penalty" ><button type="submit" class="btn btn-primary">Add</button></a></div>
            <div class="block">
                <div class="navbar navbar-inner block-header">
                    <div class="muted pull-left" style="text-align:center; float: left; width:100%;">Penalty Management<div id="msg" style="font-size:12px; color:red; text-align:center;">
                        <?php
                            if(count($flashMessages))
                            {
                                foreach ($flashMessages as $msg)
                                {
                                    echo $msg.'</blink><br>';   
                                }   
                            }
                        ?>
                    </div>

                    
                </div>
                <div class="block-content collapse in" style="overflow:visible;">
                    <table class="table table-striped">
                        <tbody>
                            <tr>
                                <th>Name</th>
                                <th>Action</th>
                            </tr>
                            <?php
                            foreach ($userNames as $value)
                            {
                            ?>
                            <tr>
                                <td><?php echo $value['employee_name']; ?></td>
                                <td><a href="/superAdmin/userReports/penaltyListAll/<?php echo $value['employee_code']?>" rel="facebox">View</a></td>
                                
                            </tr>
                            <?php
                            }
                            ?>



                        </tbody>
                    </table>
                </div>

            </div>
        </div>
    </div>