<link href="/css/facebox.css" media="screen" rel="stylesheet" type="text/css" />
  <script src="/js/facebox.js" type="text/javascript"></script>
    <script type="text/javascript">
        jQuery(document).ready(function($) {
            $('a[rel*=facebox]').facebox({
                loadingImage : '/images/loading.gif',
                closeImage   : '/images/closelabel.png'
            })
          })
  </script>    
<table class="table table-striped table-bordered table-hover dataTable no-footer" aria-describedby="dataTables-example_info">
        <tr>
            <th>Date</th>
            <th>Amount</th>
            <th>For What</th>
        </tr>
        <?php
        if(count($penalty) != '')
        {
            foreach ($penalty as $value)
            {
            ?>
                <tr>
                    <td>
                        <?php echo $value['penalty_date'];?>
                    </td>
                    <td>
                        <?php echo $value['amount'];?>
                    </td>
                    <td>
                        <?php echo $value['dis'];?>
                    </td>

                </tr>
            <?php
            }
        }
        else
        {
        ?>
            <tr>
                <td colspan="3"> No record found Yet</td>
            </tr>
        <?php
        }
        ?>
    </table>