<script src="/js/jquery.maskedinput.js" type="text/javascript"></script>
<script type="text/javascript">
$(document).ready(function(){
    
    //showTable();
    function showTable()
    {
        $.ajax({
            type        : "POST",
            url         : "/superAdmin/recordDetails/ajaxList",
            cashe       : false,
            dataType    : "html",
            beforeSend  : function()
            {
                $('#response').text('Loading...');
            },
            success     : function(data)
            {
                $("#ajx_table").html(data);
            },
            error       : function(xhr, ajaxOptions, thrownError)
            {
                alert(xhr.status);
                alert(thrownError);
            }
            
        });
    }
    



       /* var options = {  
            url:        '/superAdmin/recordDetails/ajaxList', 
            dataType: 'html',
            beforeSubmit: function()
            { 
               // $("#emsg").html('<img src="/images/photos/loading.gif" width="20" height="20" >');
            },
            
            success:    function(data) { 
           
                alert(data);
            } 
        }; 
   
        $('#detailsForm').ajaxForm(options);*/
    
        jQuery(function($){
            $("#date").mask("99/99/9999");
            
            $("#date").change(function(){
                var date= $("#date").val();
                var dates= date.split("/");

                if(dates[1] > 13)
                {
                    alert("Please enter Correct month");
                    $("#date").val('');
                }
                if(dates[0] > 32)
                {
                    alert("please enter correct date");
                    $("#date").val('');
                }
            });
            
        });
    });
</script>
<div class="span9" id="content">
    <div class="row-fluid">
        <a class="btn btn-primary " href="/superAdmin/leave">Leave form</a>
    </div>


    <div class="row-fluid">
        <div class="span12">

            <!-- block - -->

            <div class="block">
                <div class="navbar navbar-inner block-header">
                    <div class="muted pull-left">Leave Adding Form</div>
                </div>
                <div class="block-content collapse in">
                    <div class="span12">
                        <form class="form-horizontal" id="addProduct" method="post" enctype="multipart/form-data">
                            <fieldset>
                                <legend></legend>

                                <div class="control-group">
                                    <label class="control-label" for="typeahead">Leave Date</label>
                                    <div class="controls">
                                        <input type="text" name="date" id="date" class="span6" placeholder="Username" required><br />
                                    </div>
                                </div>

                                <div class="control-group">
                                    <label class="control-label" for="textarea2">Leave matter</label>
                                    <div class="controls">
                                        <textarea name="dis" id="dis" placeholder="Leave Discription" required></textarea>
                                    </div>
                                </div>
                                                                
                                <div class="form-actions">
                                    <button type="submit" name="submit" class="btn btn-primary">Save</button>
                                    <button type="reset" class="btn" id="cancel">Cancel</button>
                                </div>
                            </fieldset>
                        </form>

                    </div>
                </div>
            </div>
            <!-- /block -->


        </div>

    </div>

</div>
</div>
<script type="text/javascript">
    $("#cancel").click(function()
    {
        window.location.href= "<?php echo $this->basePath()?>/superAdmin/leave";
    });

</script>