<script src="/js/jquery.maskedinput.js" type="text/javascript"></script>
<script type="text/javascript">
function checkvalue(val) {
    
    if (val == "Half Day" || val == "Paid Half Day" ){
        document.getElementById('fromTimeJ').style.display = 'block';
        document.getElementById('toTimeJ').style.display = 'block';
    }
    else
    {
        document.getElementById('fromTimeJ').style.display = 'none';
        document.getElementById('toTimeJ').style.display = 'none';
    }    
}
    
    
$(document).ready(function(){
    
    //showTable();
    function showTable()
    {
        $.ajax({
            type        : "POST",
            url         : "/superAdmin/recordDetails/ajaxList",
            cashe       : false,
            dataType    : "html",
            beforeSend  : function()
            {
                $('#response').text('Loading...');
            },
            success     : function(data)
            {
                $("#ajx_table").html(data);
            },
            error       : function(xhr, ajaxOptions, thrownError)
            {
                alert(xhr.status);
                alert(thrownError);
            }
            
        });
    }
    
        jQuery(function($){
            $("#date").mask("99/99/9999");
            
            $("#date").change(function(){
                var date= $("#date").val();
                var dates= date.split("/");

                if(dates[1] > 13)
                {
                    alert("Please enter Correct month");
                    $("#date").val('');
                }
                if(dates[0] > 32)
                {
                    alert("please enter correct date");
                    $("#date").val('');
                }
            });
            
        });
    });
</script>
<div class="span9" id="content">
    <div class="row-fluid">
        <a class="btn btn-primary " href="/superAdmin/attendence">Go Back</a>
    </div>
    <div class="row-fluid">
        <div class="span12">

            <!-- block - -->

            <div class="block">
                <div class="navbar navbar-inner block-header">
                    <div class="muted pull-left">Employee Leave Adding Form</div>
                </div>
                <div class="block-content collapse in">
                    <div class="span12">
                        <form class="form-horizontal" id="addProduct" method="post" enctype="multipart/form-data">
                            <fieldset>
                                <legend></legend>

                                <div class="control-group">
                                    <label class="control-label" for="typeahead">Leave Date</label>
                                    <div class="controls">
                                        <input type="text" name="date" id="date" class="span6" placeholder="D/M/Y" required><br />
                                    </div>
                                </div>

				 
				<div class="control-group">
                                    <label class="control-label" for="typeahead">Employee Name</label>
                                    <div class="controls">
                                        <select name="employeeName" id="employeename">
					     
					    <?php foreach ($name as $key => $value) { ?>
					     <option value="<?php echo $value['employee_code'];?>"><?php echo $value['employee_name'];?></option>
					    <?php } ?>
					    
                                        </select>
                                          
                                    </div>
                                </div>
				
                                <div class="control-group">
                                    <label class="control-label" for="typeahead">Leave Type</label>
                                    <div class="controls">
                                        <select name="leaveType" id="leavetype" onchange='checkvalue(this.value)' selected = "<?php echo $value['leave_type']; ?>">
                                            <option value="Full Day">Full Day</option>
                                            <option value="Half Day">Half Day</option>
                                            <option value="Paid Full Day">Paid Full Day</option>
                                            <option value="Paid Half Day">Paid Half Day</option>
                                        </select>
                                    </div>
                                </div>
                                
                                <div class="control-group" style='display:none' id="fromTimJ">
                                    <label class="control-label" for="typeahead">From Time</label>
                                    <div class="controls">
                                        <input type="time" name="fromTime" id="date" class="span6" placeholder="" ><br />
                                    </div>
                                </div>
                                
                               <div class="control-group" style='display:none' id="toTimeJ">
                                    <label class="control-label" for="typeahead">To Time</label>
                                    <div class="controls">
                                        <input type="time" name="toTime" id="date" class="span6" placeholder="" ><br />
                                    </div>
                                </div>
				 


                                <div class="control-group">
                                    <label class="control-label" for="textarea2">Leave matter</label>
                                    <div class="controls">
                                        <textarea name="leaveMatter" id="leavematter" placeholder="Leave Reason" required></textarea>
                                    </div>
                                </div>
                                                                
                                <div class="form-actions">
                                    <button type="submit" name="submit" class="btn btn-primary">Save</button>
                                    <button type="reset" class="btn" id="cancel">Cancel</button>
                                </div>
                            </fieldset>
                        </form>
					    
                    </div>
                </div>
            </div>
            <!-- /block -->


        </div>

    </div>

</div>
</div>
<script type="text/javascript">
    $("#cancel").click(function()
    {
        window.location.href= "<?php echo $this->basePath()?>/superAdmin/attendence";
    });

</script>
