<script src="/js/jquery.maskedinput.js" type="text/javascript"></script>
<script type="text/javascript">
function checkvalue(val) {
    
    if (val == "Half Day" || val == "Paid Half Day" ){
        document.getElementById('fromTimeJ').style.display = 'block';
        document.getElementById('toTimeJ').style.display = 'block';
    }
    else
    {
        document.getElementById('fromTimeJ').style.display = 'none';
        document.getElementById('toTimeJ').style.display = 'none';
    }    
}



</script>











<div class="span9" id="content">
    <div class="row-fluid">
        <a class="btn btn-primary " href="/superAdmin/attendence">Go Back</a>
    </div>


    <div class="row-fluid">
        <div class="span12">

            <!-- block - -->

            <div class="block">
                <div class="navbar navbar-inner block-header">
                    <div class="muted pull-left">Employee Leave Editing Area</div>
                </div>
                <div class="block-content collapse in">
                    <div class="span12">
                        <?php 
                        foreach ($edit as $value)
                        {  
                        ?>
                        <form class="form-horizontal" id="addProduct" method="post" enctype="multipart/form-data">
                            <fieldset>
                                <legend>Edit Leave</legend>
                                
                                <div class="control-group">
                                    <label class="control-label" for="typeahead">Employee Name</label>
                                    <div class="controls">
                                        <select name="employeeName" id="employeeName">
					     
					    <?php foreach ($name as $key => $value2) { ?>
					     <option value="<?php echo $value2['employee_code'];?>" <?php if($value2['employee_code']==$value['user_id']) echo "selected"; ?>><?php echo $value2['employee_name'];?></option>
					    <?php } ?>
					    
                                        </select>
                                          
                                    </div>
                                </div>

                                <div class="control-group">
                                    <label class="control-label" for="typeahead">Date</label>
                                    <div class="controls">
                                        <input type="date" name="date" id="date" class="span6" value="<?php echo $value['leave_dates']?>" placeholder="D/M/Y" required><br />
                                    </div>
                                </div>
				
				
				
				
				  <div class="control-group">
                                    <label class="control-label" for="typeahead">Leave Type</label>
                                    <div class="controls">
                                          <select name="leaveType" id="leavetype" onchange='checkvalue(this.value)' selected = "<?php echo $value['leave_type']; ?>">
                                            <option value="Half Day" <?php if($value['leave_type']=="Half Day") echo "selected"; ?>>Half Day</option>
                                            <option value="Full Day" <?php if($value['leave_type']=="Full Day") echo "selected"; ?>>Full Day</option>
                                            <option value="Paid Half Day" <?php if($value['leave_type']=="Paid Half Day") echo "selected"; ?>>Paid Half Day</option>
                                            <option value="Paid Full Day" <?php if($value['leave_type']=="Paid Full Day") echo "selected"; ?> >Paid Full Day</option>
					    
                                        </select>
                                    </div>
                                </div>
                                
                                <div class="control-group" style='display:none' id="fromTimeJ">
                                    <label class="control-label" for="typeahead">From Time</label>
                                    <div class="controls">
                                        <input type="time" name="fromTime" id="date" class="span6"  value="<?php echo $value['from_time']?>" placeholder="" ><br />
                                    </div>
                                </div>
                                
                               <div class="control-group" style='display:none' id="toTimeJ">
                                    <label class="control-label" for="typeahead">To Time</label>
                                    <div class="controls">
                                        <input type="time" name="toTime" id="date" class="span6" value="<?php echo $value['to_time']?>"  placeholder="" ><br />
                                    </div>
                                </div>
				
				 <div class="control-group">
                                   <label class="control-label" for="textarea2">Leave matter</label>
                                    <div class="controls">
                                        <input type="text" name="desc" id="desc" placeholder="Leave Reason" value="<?php echo $value['leave_matter']?>">
                                    </div>
                                </div>
                                
				
                                <div class="form-actions">
                                    <button type="submit" name="submit" class="btn btn-primary">Save</button>
                                    <button type="reset" class="btn" id="cancel">Cancel</button>
                                </div>
                                
                            </fieldset>
                        </form>
                        <?php
                        }
                        ?>

                    </div>
                </div>
            </div>
            <!-- /block -->


        </div>

    </div>

</div>
</div>
<script type="text/javascript">
    $("#cancel").click(function()
    {
        window.location.href= "<?php echo $this->basePath()?>/superAdmin/attendence   ";
    });

</script>