<div class="block-content collapse in" style="overflow:visible;">
    <table class="table table-striped">
        <tbody>
            <tr>
                <th style="text-align:center;">Date</th>
		<th style="text-align:center;">Type</th>
		<th style="text-align:center;">Matter</th>
                <th style="text-align:center;">Status</th> 
            </tr>
            <?php
            foreach ($employeeLeaveDatas as $value)
            {
            ?>
            <tr>
                <td style="text-align:center;"><?php echo $value['leave_dates']; ?></td>
		<td style="text-align:center;"><?php echo $value['leave_type']; ?></td>
                <td style="text-align:center;"><?php echo $value['leave_matter']; ?></td>
                <td style="text-align:center;">
                    <?php 
                    if($value['status'] == 1)
                    {
                    ?>
                        <img src="/images/on.png" border="0" width="20" height="20" id="<?php echo $value['id']; ?>" class="ston">
                    <?php
                    }
                    else 
                    {
                    ?>
                        <img src="/images/off.png" border="0" width="20" height="20" id="<?php echo $value['id']; ?>" class="stof">
                    <?php
                    }
                    ?>            
                </td>
                
            </tr>
            <?php
            }
            ?>   
        </tbody>
    </table>
</div>
<div class="row-fluid">
    <div class="span12">
        <?php
            foreach ($leaveNo as $value)
            {
            ?>
        Total Leaves Left: <?php echo  $value[annual_leave]; ?>
            <?php } ?>
        </div>
    </div>
