<div class="block-content collapse in" style="overflow:visible;">
    <table class="table table-striped">
        <tbody>
            <tr>
                <th style="text-align:center;">Date</th>
                <th style="text-align:center;">Description</th>
                <th style="text-align:center;" colspan="2">Action</th>
            </tr>
            <?php
            foreach ($leaveDatas as $value)
            {
            ?>
            <tr>
                <td style="text-align:center;"><?php echo $value['leave_date']; ?></td>
                <td style="text-align:center;"><?php echo $value['desc']; ?></td>
                <td style="text-align:center;">
                    <?php 
                    if($value['status'] == 1)
                    {
                    ?>
                        <img src="/images/on.png" border="0" width="20" height="20" id="<?php echo $value['id']; ?>" class="ston">
                    <?php
                    }
                    else 
                    {
                    ?>
                        <img src="/images/off.png" border="0" width="20" height="20" id="<?php echo $value['id']; ?>" class="stof">
                    <?php
                    }
                    ?>            
                </td>
                <td>
                    <a href="/superAdmin/leave/edit/<?php echo $value['id'];?>"><img src="/images/edit.gif" border="0" width="40" height="40" id="">
                </td>
            </tr>
            <?php
            }
            ?>
            

           
        </tbody>
    </table>
</div>
