<div class="span9" id="content">
    <div class="row-fluid">
        <a class="btn btn-primary " href="/superAdmin/leave">Go Back</a>
    </div>


    <div class="row-fluid">
        <div class="span12">

            <!-- block - -->

            <div class="block">
                <div class="navbar navbar-inner block-header">
                    <div class="muted pull-left">Leave Editing Area</div>
                </div>
                <div class="block-content collapse in">
                    <div class="span12">
                        <?php 
                        foreach ($edit as $value)
                        {
                        ?>
                        <form class="form-horizontal" id="addProduct" method="post" enctype="multipart/form-data">
                            <fieldset>
                                <legend>Edit Leave</legend>

                                <div class="control-group">
                                    <label class="control-label" for="typeahead">Date</label>
                                    <div class="controls">
                                        <input type="date" name="date" id="date" class="span6" value="<?php echo $value['leave_date']?>" placeholder="D/M/Y" required><br />
                                    </div>
                                </div>

                                <div class="control-group">
                                    <label class="control-label" for="textarea2">Reason</label>
                                    <div class="controls">
                                        <input type="text" name="desc" id="desc" placeholder="Leave Reason" value="<?php echo $value['desc']?>">
                                    </div>
                                </div>
                                <div class="form-actions">
                                    <button type="submit" name="submit" class="btn btn-primary">Save</button>
                                    <button type="reset" class="btn" id="cancel">Cancel</button>
                                </div>
                            </fieldset>
                        </form>
                        <?php
                        }
                        ?>

                    </div>
                </div>
            </div>
            <!-- /block -->


        </div>

    </div>

</div>
</div>
<script type="text/javascript">
    $("#cancel").click(function()
    {
        window.location.href= "<?php echo $this->basePath()?>/superAdmin/leave";
    });

</script>