<div class="block-content collapse in" style="overflow:visible;">
    <table class="table table-striped">
        <tbody>
            <tr>
                <th style="text-align:center;">Date</th>
                <th style="text-align:center;">Title</th>
                <th style="text-align:center;">Note</th>
            </tr>
            <?php
            foreach ($notesDatas as $value)
		
            {		
            ?>
            <tr>
                <td style="text-align:center;"><?php echo $value['notes_date']; ?></td>
                <td style="text-align:center;"><?php echo $value['title']; ?></td>
		<td style="text-align:center;"><?php echo $value['note']; ?></td>
                <td style="text-align:center;">
                    <a href="/superAdmin/notes/edit/<?php echo $employee; ?>/<?php echo $value['id'];?>"><img src="/images/edit.gif" border="0" width="40" height="40" id=""></a>
		    
                    <a href="/superAdmin/notes/delete/<?php echo $employee; ?>/<?php echo $value['id'];?>"><img src="/images/delete.png" border="0" width="30" height="30" style="padding-left: 20px;" class ="del"></a>
                </td>
            </tr>
            <?php
            }
            ?>
            

           
        </tbody>
    </table>
</div>
