
<div class="block-content collapse in" style="overflow:visible;">
    <table class="table table-striped">
        <tbody>
            <tr>
                <th style="text-align:center;">Date</th>
                <th style="text-align:center;">Title</th>
                <th style="text-align:center;">Note</th>
            </tr>
            <?php
            foreach ($notesDatas as $value)
		
            {	
                
            ?>
            <tr>
        <td style="text-align:center;"><a href="/superAdmin/notes/preview/<?php echo $value['id'];?>" rel="facebox"><?php echo $value['notes_date']; ?></a></td>
        <td style="text-align:center;"><a href="/superAdmin/notes/preview/<?php echo $value['id'];?>" rel="facebox"><?php echo $value['title']; ?></a></td> 

                <td style="text-align:center;">
                    <a href="/superAdmin/notes/edit/<?php echo $employee; ?>/<?php echo $value['id'];?>"><img src="/images/edit.gif" border="0" width="40" height="40" id=""></a>
		    
                    <a href="/superAdmin/notes/delete/<?php echo $employee; ?>/<?php echo $value['id'];?>" rel="facebox"><img src="/images/delete.png" border="0" width="30" height="30" style="padding-left: 20px;" class ="del"></a>
                </td>
            </tr>
            <?php
            }
            ?>
            

           
        </tbody>
    </table>
</div>
<script src="/js/facebox.js" type="text/javascript"></script>
<script type="text/javascript">
    jQuery(document).ready(function($) {
      $('a[rel*=facebox]').facebox({
        loadingImage : '/images/loading.gif',
        closeImage   : '/images/closelabel.png'
      });
      
    }); 
</script>