<script src="/js/jquery.maskedinput.js" type="text/javascript"></script>
<script type="text/javascript" src="/js/tinymce/tinymce.min.js"></script>

<script>
tinymce.init({
    selector: "textarea",
    theme: "modern",
    height: 250,
    editor_encoding: "raw",
    plugins: [
         "advlist autolink link image lists charmap print preview hr anchor pagebreak spellchecker",
         "searchreplace wordcount visualblocks visualchars code fullscreen insertdatetime media nonbreaking",
         "save table contextmenu directionality emoticons template paste textcolor"
   ],
   content_css: "css/content.css",
   toolbar: "insertfile undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | l      ink image | print preview media fullpage | forecolor backcolor emoticons", 
   style_formats: [
        {title: 'Bold text', inline: 'b'},
        {title: 'Red text', inline: 'span', styles: {color: '#ff0000'}},
        {title: 'Red header', block: 'h1', styles: {color: '#ff0000'}},
        {title: 'Example 1', inline: 'span', classes: 'example1'},
        {title: 'Example 2', inline: 'span', classes: 'example2'},
        {title: 'Table styles'},
        {title: 'Table row 1', selector: 'tr', classes: 'tablerow1'}
    ]
 }); 
</script>


<script src="/js/jquery.maskedinput.js" type="text/javascript"></script>
<div class="span9" id="content">
    <div class="row-fluid">
        <a class="btn btn-primary " href="/superAdmin/notes/cancel/<?php echo $employee; ?>">Go Back</a>
    </div>


    <div class="row-fluid">
        <div class="span12">

            <!-- block - -->

            <div class="block">
                <div class="navbar navbar-inner block-header">
                    <div class="muted pull-left"> Note Editing Area</div>
                </div>
                <div class="block-content collapse in">
                    <div class="span12">
                        <?php 
                        foreach ($notesDatas as $value)
                        {  
                        ?>
                        <form class="form-horizontal" id="addProduct" method="post" enctype="multipart/form-data">
                            <fieldset>
                                <legend>Edit Note</legend>
                                
                                

                                <div class="control-group">
                                    <label class="control-label" for="typeahead">Date</label>
                                    <div class="controls">
                                        <input type="date" name="date" id="date" class="span4" value="<?php echo $value['notes_date']?>" placeholder="D/M/Y" required><br />
                                    </div>
                                </div>
				
				
				<div class="control-group">
                                    <label class="control-label" for="typeahead">Title</label>
                                    <div class="controls">
                                        <input type="text" name="title" id="title" class="span6" placeholder="Enter here.." value="<?php echo $value['title']?>" required><br />
                                    </div>
                                </div>
				  
			        <div class="control-group">
                                   <label class="control-label" for="textarea2">Note</label>
                                    <div class="controls">
                                        <textarea name="note" id="note" class="span6"> <?php echo $value['note']?></textarea> 
                                    </div>
                                </div>
                                
				
                                <div class="form-actions">
                                    <button type="submit" name="submit" class="btn btn-primary">Save</button>
                                    <button type="reset" class="btn" id="cancel">Cancel</button>
                                </div>
                                
                            </fieldset>
                        </form>
                        <?php
                        }
                        ?>

                    </div>
                </div>
            </div>
            <!-- /block -->


        </div>

    </div>

</div>
</div>
 <script type="text/javascript">
    $("#cancel").click(function()
    { 
	
          window.location.href= "/superAdmin/notes/cancel/<?php echo $employee; ?>";
    })
 </script>