<script src="/js/jquery.maskedinput.js" type="text/javascript"></script>
<div class="span9" id="content">
    <div class="row-fluid">
        <a class="btn btn-primary " href="/superAdmin/notes/cancel/<?php echo $employee; ?>">Go Back</a>
    </div>


    <div class="row-fluid">
        <div class="span12">

            <!-- block - -->

            <div class="block">
                <div class="navbar navbar-inner block-header">
                    <div class="muted pull-left"> Note Editing Area</div>
                </div>
                <div class="block-content collapse in">
                    <div class="span12">
                        <?php 
                        foreach ($notesDatas as $value)
                        {  
                        ?>
                        <form class="form-horizontal" id="addProduct" method="post" enctype="multipart/form-data">
                            <fieldset>
                                <legend>Edit Note</legend>
                                
                                

                                <div class="control-group">
                                    <label class="control-label" for="typeahead">Date</label>
                                    <div class="controls">
                                        <input type="date" name="date" id="date" class="span4" value="<?php echo $value['notes_date']?>" placeholder="D/M/Y" required><br />
                                    </div>
                                </div>
				
				
				<div class="control-group">
                                    <label class="control-label" for="typeahead">Title</label>
                                    <div class="controls">
                                        <input type="text" name="title" id="title" class="span6" placeholder="Enter here.." value="<?php echo $value['title']?>" required><br />
                                    </div>
                                </div>
				  
			        <div class="control-group">
                                   <label class="control-label" for="textarea2">Note</label>
                                    <div class="controls">
                                        <input type="text" name="note" id="note" class="span6" placeholder="Enter here..." value="<?php echo $value['note']?>">  
                                    </div>
                                </div>
                                
				
                                <div class="form-actions">
                                    <button type="submit" name="submit" class="btn btn-primary">Save</button>
                                    <button type="reset" class="btn" id="cancel">Cancel</button>
                                </div>
                                
                            </fieldset>
                        </form>
                        <?php
                        }
                        ?>

                    </div>
                </div>
            </div>
            <!-- /block -->


        </div>

    </div>

</div>
</div>
 <script type="text/javascript">
    $("#cancel").click(function()
    { 
	
          window.location.href= "/superAdmin/notes/cancel/<?php echo $employee; ?>";
    })
 </script>