<script type="text/javascript">

    
    $(document).ready(function() {
        showTable();

    });
    
    function showTable()
    {
       var code = <?php echo $employee; ?>;   
       
        $.ajax({

            type:"POST",
            url:"/superAdmin/notes/ajaxList/"+code,
            cache:false,
            data:{},
            dataType:"html",
            success:function(data)
            {
                $("#ajx_table").html(data);
            }
        });
    }
    
     //Delete
    $('.del').live('click',function()
    {   var code1 = <?php echo $employee; ?>;
        $.ajax({
            type:"POST",
            url:"/superAdmin/notes/delete/"+code1,
            cache:false,
            data:{},
            dataType:"html",
            success:function(data)
            {   
                $("#msg").html(data);
                $('#msg').delay(2000).fadeOut();
                showTable();
            }
        });

    });


       
    
   
   


</script>

<style type="text/css">
    .ston { cursor: pointer;} .stof { cursor: pointer;} .del { cursor: pointer;}

</style>

<div class="span99" id="content">
    <div class="row-fluid">
      	<div class="navbar">
           	
        </div>
    </div>
    <div class="row-fluid">
        <div class="span12">
            <div class="row-fluid">
        <a class="btn btn-primary " id="popup"  href="/superAdmin/notes/back/<?php echo $employee; ?>">Go Back</a>
                    <a href="/superAdmin/notes/add/<?php echo $employee; ?>" ><button type="submit" class="btn btn-primary" style="margin-left:885px;">Add</button></a>

    </div>

            <div class="block">
                <div class="navbar navbar-inner block-header">
                    <div class="muted pull-left" style="text-align:center; float: left; width:100%;"> Notes<div id="msg" style="font-size:12px; color:red; text-align:center;">
                        <?php
                            if(count($flashMessages))
                            {
                                foreach ($flashMessages as $msg)
                                {
                                    echo $msg.'</blink><br>';   
                                }   
                            }
                        ?>
                    </div>

                    
                </div>
                <div id="ajx_table"></div>
            </div>
        </div>
    </div>