<link href="/css/facebox.css" media="screen" rel="stylesheet" type="text/css" />
<script src="/js/facebox.js" type="text/javascript"></script>
  <script type="text/javascript">
    jQuery(document).ready(function($) {
      $('a[rel*=facebox]').facebox({
        loadingImage : '/images/loading.gif',
        closeImage   : '/images/closelabel.png'
      });
      
      $("#popup").click(function(){ 
      $('#popup').prop('rel', facebox);
    });
    });
  </script>
<div class="span9" id="content">
    <div class="row-fluid">
         <a class="btn btn-primary " href="/superAdmin/notes/cancel/<?php echo $employee; ?>">Go Back</a>
    </div>
    <div class="row-fluid">
        <div class="span12">

            <!-- block - -->

            <div class="block">
                <div class="navbar navbar-inner block-header">
                    <div class="muted pull-left">Employee Note </div>
                </div>
                <div class="block-content collapse in">
                    <div class="span12">
                        <form class="form-horizontal" id="addProduct" method="post" enctype="multipart/form-data">
                            <fieldset>
                                <legend></legend>

                                 
				
                                <td style="text-align:center;"><a href="#"</a><?php echo $value['note']; ?></td>
				  


                                <div class="control-group">
                                    <label class="control-label" for="textarea2">Note</label>
                                    <div class="controls">
                                        <textarea name="note" id="note" class="span6"   placeholder="Enter here.." required></textarea>
                                    </div>
                                </div>
                                                                
                       
                            </fieldset>
                        </form>
					    
                    </div>
                </div>
            </div>
            <!-- /block -->


        </div>

    </div>

</div>
</div>
<script type="text/javascript">
    $("#cancel").click(function()
    {
          window.location.href= "/superAdmin/notes/cancel/<?php echo $employee; ?>";

</script>
