 <script type="text/javascript">
    var i=2;
    function increase()
    {
	var cnt= i++;
        $('#cnt').val(cnt);
        $.ajax({
            type:"POST",
            url:"/superAdmin/rating/ajaxTable",
            cache:false,
            data: { cnt:cnt },
            dataType:"html",
            success:function(data)
            {
                $("#result").append(data);   
            }
        });
    }  
    
    $('.cls').live('click',function()
    {
        var id= $(this).attr('id');
        var delId= id.split('_');
        cnt = document.getElementById('cnt').value--;
        $("#cp"+delId[1]).remove();
    });
</script>
<style type="text/css">
    .add { cursor: pointer;}
    
     .cls{ cursor: pointer; }

</style>
<div class="span9" id="content">
    <div class="row-fluid">
        <a class="btn btn-primary" href="/superAdmin/rating/cancel/<?php echo $employee; ?>">Go Back</a>
    </div>

    
    <div class="row-fluid">
        <div class="span12">

            <!-- block - -->

            <div class="block">
                <div class="navbar navbar-inner block-header">
                    <div class="muted pull-left">Add Skill and Rating</div>
                </div>
                <div class="block-content collapse in">
                    <div class="span12">
                        <form class="form-horizontal" id="addProduct" method="post" enctype="multipart/form-data">
                            <fieldset>
                                <legend></legend>
                                
                               
                                
                <div class="control-group" id="cp<?php echo $this->count ;?>">
    <div class="controls" style="margin-left: 0;">                
                <table>
                    <tr>
                        <td> Skill:
                            <select name="skill[]">  
                                <?php foreach ($skillDatas as $value) {?>
                                <option value="<?php echo $value['skill']; ?>"><?php    echo $value['skill']; ?></option>
                                <?php } ?>
                            </select>                 
                        </td>
                        <td> Rating: <input name="rating[]" type="number" min="1" max="5"><b style="font-size: 20px; color: red;">/5</b></td>
                    </tr>
                    </table> 
    </div>
                </div>
                    
                    <div id="result"> </div>
                    
                
                    <div id="skillnew" style="float: left; padding-left: 10px;" class="add" onclick="increase()"><input name="cnt"  id="cnt" value="1" type="hidden" ></br>
                                    <image src="/images/add.png" height="40px" width="40px"/>Add More<input type="hidden" id="noskill" name="noskill" value="2"></div>

                             
                                
                                <div class="form-actions">
                                    <button type="submit" name="submit" class="btn btn-primary">Save</button>
                                    <button type="reset" class="btn" id="cancel">Cancel</button>
                                </div>
                                
                                
                                </fieldset>
                        </form>

                    </div>
                </div>
            </div>
            <!-- /block -->


        </div>

    </div>

</div>
</div>
<script type="text/javascript">
    $("#cancel").click(function()
    {
        window.location.href= "/superAdmin/rating/cancel/<?php echo $employee; ?>";
    });

</script>
