<div class="block-content collapse in" style="overflow:visible;">
    <table class="table table-striped">
        <tbody>
            <tr>
                <th style="text-align:center;">Skill</th>
                <th style="text-align:center;">Rating</th>
                <th style="text-align:center;">Action</th>
            </tr>
            <?php
            foreach ($ratingDatas as $value)
            {
            ?>
            <tr>
                <td style="text-align:center;"><?php echo $value['skill']; ?></td>
                <td style="text-align:center;"><?php echo $value['rating']; ?></td>
                <td style="text-align:center;">
                    <a href="/superAdmin/rating/edit/<?php echo $employee; ?>/<?php echo $value['id'];?>"><img src="/images/edit.gif" border="0" width="40" height="40" id=""></a>
                    <a href="/superAdmin/rating/delete/<?php echo $employee; ?>/<?php echo $value['id'];?>"><img src="/images/delete.png" border="0" width="30" height="30" style="padding-left: 20px;" class ="del"></a>
                </td>
            </tr>
            <?php
            }
            ?>
            

           
        </tbody>
    </table>
</div>
