<div class="control-group" id="cp<?php echo $this->count ;?>">
    <div class="controls" style="margin-left: 0;">
<table>
<tr>
                        <td> Skill:
                            <select name="skill[]">  
                                <?php foreach ($skillDatas as $value) {?>
                                <option value="<?php echo $value['skill']; ?>"><?php    echo $value['skill']; ?></option>
                                <?php } ?>
                                
                          </select>                 
                        </td>
                        <td> Rating: <input name="rating[]" type="number" min="1" max="5"><b style="font-size: 20px; color: red;">/5</b></td>
                        <td><img src="/images/minus.png" border="0" height="20px" width="20px" title="delete" id="close_<?php echo $this->count ;?>" class="cls"></td>
                    </tr>
</table>
            </div>
</div>