<div class="span9" id="content">
    <div class="row-fluid">
        <a class="btn btn-primary" href="/superAdmin/rating/cancel/<?php echo $employee; ?>">Go Back</a>
    </div>

    
    <div class="row-fluid">
        <div class="span12">

            <!-- block - -->

            <div class="block">
                <div class="navbar navbar-inner block-header">
                    <div class="muted pull-left">Add Skill and Rating</div>
                </div>
                <div class="block-content collapse in">
                    <div class="span12">
                        <form class="form-horizontal" id="addProduct" method="post" enctype="multipart/form-data">
                            <fieldset>
                                <legend></legend>
                                
                               
                                

                <table>
                    <?php
                        foreach ($ratingDatas as $value)
                        {
                    ?>
                    <tr>
                        <td> Skill: <input name="skill" type="text" value="<?php echo $value['skill']; ?>"> Rating: <input name="rating" type="text" value="<?php echo $value['rating']; ?>"><b style="font-size: 20px; color: red;">/5</b></td>
                    </tr>
                   <?php  } ?>
                </table>
                                <div class="form-actions">
                                    <button type="submit" name="submit" class="btn btn-primary">Save</button>
                                    <button type="reset" class="btn" id="cancel">Cancel</button>
                                </div>
                                
                                
                                </fieldset>
                        </form>

                    </div>
                </div>
            </div>
            <!-- /block -->


        </div>

    </div>

</div>
</div>
<script type="text/javascript">
    $("#cancel").click(function()
    {
        window.location.href= "/superAdmin/rating/cancel/<?php echo $employee; ?>";
    });

</script>
