<div class="block-content collapse in">
    <?php print_r($salary); print_r($records); exit(); ?>
    <table class="table table-striped">
        <thead>
            <tr>
                <th style="text-align:center;">Date</th>
                <th style="text-align:center;">TWorkingT</th>
                <th style="text-align:center;">TOutT</th>
                <th style="text-align:center;">OT</th>
                <th style="text-align:center;">Total</th>
            </tr>
            <?php
            if(count($records) != '')
            {
                foreach ($records as $value)
                {
                ?>
                <tr>
                    <td style="text-align:center;"><?php echo $value['dates']; ?></td>
                    <td style="text-align:center;"><?php echo $value['totalIn']; ?></td>
                    <td style="text-align:center;"><?php echo $value['totalOut']; ?></td>
                    <td style="text-align:center;"><?php echo $value['over_time']; ?></td>  
                </tr>
                <?php
                }
            }
            else
            {
            ?>
                <tr>
                    <td colspan="6" style="text-align:center;">Oops no records founds..</td>
                </tr>
            <?php   
            }
            ?>
        </thead>
        <tbody>
        
           
        </tbody>
    </table>
</div>