<script src="/js/jquery.maskedinput.js" type="text/javascript"></script>
<script type="text/javascript">
$(document).ready(function(){
    
    //showTable();
    function showTable()
    {
        $.ajax({
            type        : "POST",
            url         : "/superAdmin/recordDetails/ajaxList",
            cashe       : false,
            dataType    : "html",
            beforeSend  : function()
            {
                $('#response').text('Loading...');
            },
            success     : function(data)
            {
                $("#ajx_table").html(data);
            },
            error       : function(xhr, ajaxOptions, thrownError)
            {
                alert(xhr.status);
                alert(thrownError);
            }
            
        });
    }
    



       /* var options = {  
            url:        '/superAdmin/recordDetails/ajaxList', 
            dataType: 'html',
            beforeSubmit: function()
            { 
               // $("#emsg").html('<img src="/images/photos/loading.gif" width="20" height="20" >');
            },
            
            success:    function(data) { 
           
                alert(data);
            } 
        }; 
   
        $('#detailsForm').ajaxForm(options);*/
    
        jQuery(function($){
            $("#date1").mask("99/99/9999");
            $("#date2").mask("99/99/9999");

            $("#date1").change(function(){
                var date= $("#date1").val();
                var dates= date.split("/");

                if(dates[1] > 13)
                {
                    alert("Please enter Correct month");
                    $("#date1").val('');
                }
                if(dates[0] > 32)
                {
                    alert("please enter correct date");
                    $("#date1").val('');
                }
            });
            $("#date2").change(function(){
                var date= $("#date2").val();
                var dates= date.split("/");

                if(dates[1] > 13)
                {
                    alert("Please enter Correct month");
                    $("#date2").val('');
                }
                if(dates[0] > 32)
                {
                    alert("please enter correct date");
                     $("#date2").val('');
                }
            });

        });
    });
</script>


<div class="span99" id="content">
    <div class="row-fluid">
      	<div class="navbar">
           	
        </div>
    </div>
    <div class="row-fluid">
        <div class="span12">
            
            <div class="block">
                <div class="navbar navbar-inner block-header">
                    <div class="muted pull-left" style="text-align:center; float: left; width:100%;">Employee Records Listings<div id="msg" style="font-size:12px; color:red; text-align:center;">
                        <?php
                            if(count($flashMessages))
                            {
                                foreach ($flashMessages as $msg)
                                {
                                    echo $msg.'</blink><br>';   
                                }   
                            }
                        ?>
                    </div>
                        
                    <div class="muted pull-left">
                        <form id="detailsForm" name="detailsForm" method="post" action="/superAdmin/recordDetails/userDetails">
                            <select id="name" name="name" required>
                                <option value="">Name please</option>
                                <?php
                                foreach ($userNames as $value)
                                {
                                ?>
                                <option value="<?php echo $value['employee_code']?>"><?php echo $value['employee_name']?></option>
                                <?php
                                }
                                ?>
                                
                            </select>
                            <input type="text" name="date1" id="date1">
                            <input type="text" name="date2" id="date2">
                            <input type="submit" name="submit" value="Submit" style="margin-bottom: 11px; padding: 3px; width: 99px;">
                        </form>
                    </div>

                    
                </div>
                <div class="block-content collapse in">
                    <table class="table table-striped">
                        <thead>
                            <tr>
                                <th style="text-align:center;">Date</th>
                                <th style="text-align:center;">In Time</th>
                                <th style="text-align:center;">WorkingHours</th>
                                <th style="text-align:center;">OT</th>
                            </tr>
                            <?php
                            if(count($records) != '')
                            {
                                foreach ($records as $value)
                                {
                                ?>
                                <tr>
                                    <td style="text-align:center;"><?php echo $value['dates']; ?></td>
                                    <td style="text-align:center;"><?php echo $value['in_time'].'-'; if($value['late_by'] !='') { echo "<style=\"color:red;\">(late by -".$value['late_by'].")"; } ?></td>
                                    <td style="text-align:center;"><?php echo $value['total_in']; ?></td>
                                    <td style="text-align:center;"><?php echo $value['over_time']; ?></td>  
                                </tr>
                                <?php
                                }
                                ?>
                                    <tr>
                                        <td style="text-align:center;" colspan="2">Total Working Hours</td><td style="text-align:center; color: red;"><?php echo $tt= $this->totWork; ?></td><td style="text-align:center; color: red;"><?php echo $ot= $this->ot; ?></td>
                                    </tr>
                                    <tr>
                                        <td style="text-align:center;" colspan="3">Grand Total Working Hours</td>
                                        <td style="text-align:center; color: red;">
                                            <?php
                                                $tth= explode(':',$tt);
                                                $oth= explode(':',$ot);
                                                $h= $tth['0']+$oth['0'];
                                                $m= $tth['1']+$oth['1'];
                                                if($m >= 60)
                                                {
                                                    $hours=$h+1;
                                                    echo $hours." Hours";
                                                }
                                                else
                                                {
                                                    echo $h. " Hours";
                                                }
                                            ?>
                                        </td>
                                    </tr>
                                <?php
                            }
                            else
                            {
                            ?>
                                <tr>
                                    <td colspan="6" style="text-align:center;">Oops no records founds..</td>
                                </tr>
                            <?php   
                            }
                            ?>
                                
                                
                        </thead>
                    </table>
                </div>
            </div>
        </div>
    </div>
                 
<div id="response"></div>