 <script type="text/javascript">
    var i=2;
    function increase()
    {
	var cnt= i++;
        $('#cnt').val(cnt);
        $.ajax({
            type:"POST",
            url:"/superAdmin/rating/ajaxTable",
            cache:false,
            data: { cnt:cnt },
            dataType:"html",
            success:function(data)
            {
                $("#result").append(data);   
            }
        });
    }  
    
    $('.cls').live('click',function()
    {
        var id= $(this).attr('id');
        var delId= id.split('_');
        cnt = document.getElementById('cnt').value--;
        $("#cp"+delId[1]).remove();
    });
</script>
<style type="text/css">
    .add { cursor: pointer;}
    
     .cls{ cursor: pointer; }

</style>

<div class="span99" id="content">
    <div class="row-fluid">
      	<div class="navbar">
           	
        </div>
    </div>
    <div class="row-fluid">
        <div class="span12">
            <div class="block">
                <div class="navbar navbar-inner block-header">
                    <div class="muted pull-left" style="text-align:center; float: left; width:100%;">Punch Records<div id="msg" style="font-size:12px; color:red; text-align:center;">
                <!--        <?php
                            if(count($flashMessages))
                            {
                                foreach ($flashMessages as $msg)
                                {
                                    echo $msg.'</blink><br>';   
                                }   
                            }
                        ?> -->
                    </div>
                </div>

    <form id="detailsForm" name="detailsForm" method="post" action="/superAdmin/edit/updateRecord">
        <div class="row-fluid">
            <?php foreach ($records as $value) { 
            static $i = 0; 
            static $j = 0; 
            if($i == 0)
            {
               echo '<h3> Date: '. $value['punch_date'] . '</h3>';
               echo '<h4> Name: '. $value['employee_name'] . '</h4>'; ?>
            
                <table class="table table-striped">
                    <tbody>
                     <tr> 
                        <th style="text-align:left;">In Time</th>
                        <th style="text-align:left;">Out Time</th>
                     </tr>
                    <?php 
            }
                if($value['in_time']!= NULL)
                {
                   echo '<tr><td><input type="time" value="'. $value['in_time'] .'" name="inTime[]">'; 
                   echo '<input type="hidden" name="inTableId[]" value="'. $value['id'].'"> </td> ';
                   $i++;
                   if($value['out_time']!=NULL){
                   echo '<td><input type="time" value="'. $value['out_time'] . '" name="outTime[]">';
                   echo '<input type="hidden" name="outTableId[]" value="'. $value['id'].'"> </td> </tr>';
                   $j++;
                   }
                }
               else if($value['out_time']!=NULL){
                   echo '<td><input type="time" value="'. $value['out_time'] . '" name="outTime[]">';
                   echo '<input type="hidden" name="outTableId[]" value="'. $value['id'].'"> </td> </tr>';
                   $j++;
               }
                   
            
            ?>
            
            <?php
            
            }
            echo '<input type="hidden" name="totalInRecords" value="'. $i.'">';
            echo '<input type="hidden" name="totalOutRecords" value="'. $j.'">';
            $total = $i + $j;
            echo '<input type="hidden" name="totalRecords" value="'. $total.'">';
            ?>
            </tbody>
            </table> 
            <div id="ajax_table"></div>
            <div class="form-actions">
                                    <span id="skillnew" style="float: right;" class="add" onclick="increase()"><input name="cnt"  id="cnt" value="1" type="hidden" >
                                    <image src="/images/add.png" height="40px" width="40px"/>Add<input type="hidden" id="noskill" name="noskill" value="2"></span>

                                    <button type="submit" name="submit" class="btn btn-primary">Save</button>
                                    <button type="reset" class="btn" id="cancel">Cancel</button>
            </div>
        </div>
    </form>
    
                    
                    </div>
        </div>
    </div>