<style type="text/css">
    .add { cursor: pointer;}
    
     .cls{ cursor: pointer; }

</style>

<div class="span99" id="content">
    <div class="row-fluid">
      	<div class="navbar">
           	
        </div>
    </div>
    <div class="row-fluid">
        <div class="span12">
            <div class="block">
                <div class="navbar navbar-inner block-header">
                    <div class="muted pull-left" style="text-align:center; float: left; width:100%;">Punch Records<div id="msg" style="font-size:12px; color:red; text-align:center;">
                <!--        <?php
                            if(count($flashMessages))
                            {
                                foreach ($flashMessages as $msg)
                                {
                                    echo $msg.'</blink><br>';   
                                }   
                            }
                        ?> -->
                    </div>
                </div>

    <form id="detailsForm" name="detailsForm" method="post" action="/superAdmin/edit/updateRecord">
        <div class="row-fluid">
            <?php foreach ($records as $value) { 
            static $i = 0; 
            static $j = 0; 
            static $count = 0;
            if($i == 0)
            {
               echo '<h3> Date: '. $value['punch_date'] . '</h3>';
               echo '<h4> Name: '. $value['employee_name'] . '</h4>'; 
               echo '<input type="hidden" name="monthly_table_id" value="'. $value['monthly_table_id'].'">'; ?>
            
                <table class="table table-striped">
                    <tbody>
                     <tr> 
                        <th style="text-align:left;">In Time</th>
                        <th style="text-align:left;">Out Time</th>
                        <th style="text-align:left;"></th>
                     </tr>
                     
            </tbody>
            </table>
                    <?php 
            }
                if($value['in_time']!= NULL)
                {
                   echo '<div class="control-group" id="cp'.$count.'">';
                   echo '<table class="table table-striped"><tbody><tr><td><input type="time" value="'. $value['in_time'] .'" name="inTime[]">'; 
                   echo '<input type="hidden" name="inTableId[]" value="'. $value['id'].'"> </td> ';
                   $i++;
                   if($value['out_time']!=NULL){
                   echo '<td><input type="time" value="'. $value['out_time'] . '" name="outTime[]">';
                   echo '<input type="hidden" name="outTableId[]" value="'. $value['id'].'"> </td>';
                   echo '</tr></tbody></table></div>';
                   $j++;
                   $count++;
                   }
                }
               else if($value['out_time']!=NULL){
                   echo '<td><input type="time" value="'. $value['out_time'] . '" name="outTime[]">';
                   echo '<input type="hidden" name="outTableId[]" value="'. $value['id'].'"> </td>';
                   echo '</tr></tbody></table></div>';
                   $j++;
                   $count++;
               }
                   
            
            ?>
            
            <?php
            
            }
            echo '<input type="hidden" name="totalInRecords" id = "totalInRecords" value="'. $i.'">';
            echo '<input type="hidden" name="totalOutRecords" id = "totalOutRecords" value="'. $j.'">';
            echo '<input type="hidden" name="totalRecords" value="'. $count.'" id="totalRecords" >';
            ?> 
            <div class="form-actions">
                                    <button type="submit" name="submit" class="btn btn-primary">Update</button>
                                    <button type="reset" class="btn" id="cancel">Cancel</button>
            </div>
        </div>
    </form>
    
                    
                    </div>
        </div>
    </div>