
    <form id="detailsForm" name="detailsForm" method="post" action="/superAdmin/edit/editRecord">
        <div class="row-fluid">
            <?php foreach ($record as $key => $value) { ?>

            <h3>Punch Record</h3>
            <textarea rows="10" cols="20" style="margin: 0px 0px 10px; width: 628px; height: 206px;">
                <?php echo $value['punch_records']; //print_r($value); ?>

            </textarea>
            <div class="form-actions">
                                    <button type="submit" name="submit" class="btn btn-primary">Save</button>
                                    <button type="reset" class="btn" id="cancel">Cancel</button>
            </div>
            <?php } ?>
        </div>
    </form>
    