<div class="span99" id="content">
    <div class="row-fluid">
      	<div class="navbar">
           	
        </div>
    </div>
    <div class="row-fluid">
        <div class="span12">
            
            <div class="block">
                <div class="navbar navbar-inner block-header">
                    <div class="muted pull-left" style="text-align:center; float: left; width:100%;">Edit Employee Record<div id="msg" style="font-size:12px; color:red; text-align:center;">
                        <?php
                            if(count($flashMessages))
                            {
                                foreach ($flashMessages as $msg)
                                {
                                    echo $msg.'</blink><br>';   
                                }   
                            }
                        ?>
                    </div>
                        
                    <div class="muted pull-left">
                        <div class="block-content collapse in">
                    <div class="span12">
                        <form id="detailsForm" name="detailsForm" method="post" action="/superAdmin/edit/editRecord">
                            <fieldset>
                            Name:<select id="name" name="name" required>
                                <option value="">Name please</option>
                                <?php
                                foreach ($userNames as $value)
                                {
                                ?>
                                <option value="<?php echo $value['employee_code']?>"><?php echo $value['employee_name']?></option>
                                <?php
                                }
                                ?>
                                
                            </select>
                            Date:
                            <input type="date" name="date1" id="date1">
                            <input type="submit" name="submit" value="Submit" style="margin-bottom: 11px; padding: 3px; width: 99px;">
                            </fieldset>
                        </form>
                    </div>

                    
                </div>

                    
                    
                    
            </div>
        </div>
    </div>
                 
<div id="response"></div>