<div class="block-content collapse in" style="overflow:visible;">
    <table class="table table-striped">
        <tbody>
            <tr>
                <th style="text-align:center;">Meal</th>
                <th style="text-align:center;">From Time</th>
                <th style="text-align:center;">To Time</th>
                <th style="text-align:center;">Status</th>
                <th style="text-align:center;" colspan="2">Action</th>
            </tr>
            <?php
            foreach ($policyDatas as $value)
            {
            ?>
            <tr>
                <td style="text-align:center;"><?php echo $value['meal_type']; ?></td>
                <td style="text-align:center;"><?php echo $value['start_time']; ?></td>
                <td style="text-align:center;"><?php echo $value['stop_time']; ?></td>
                <td style="text-align:center;">
                    <?php 
                    if($value['status'] == 1)
                    {
                    ?>
                        <img src="/images/on.png" border="0" width="20" height="20" id="<?php echo $value['id']; ?>" class="ston">
                    <?php
                    }
                    else 
                    {
                    ?>
                        <img src="/images/off.png" border="0" width="20" height="20" id="<?php echo $value['id']; ?>" class="stof">
                    <?php
                    }
                    ?>            
                </td>
                <td>
                    <a href="/superAdmin/mealPolicy/edit/<?php echo $value['id'];?>"><img src="/images/edit.gif" border="0" width="40" height="40" id="">
                </td>
            </tr>
            <?php
            }
            ?>
            

           
        </tbody>
    </table>
</div>
