<div class="span9" id="content">
    <div class="row-fluid">
        <a class="btn btn-primary " href="/superAdmin/mealPolicy">Go Back</a>
    </div>


    <div class="row-fluid">
        <div class="span12">

            <!-- block - -->

            <div class="block">
                <div class="navbar navbar-inner block-header">
                    <div class="muted pull-left">Edit Meal Policy</div>
                </div>
                <div class="block-content collapse in">
                    <div class="span12">
                        <?php 
                        foreach ($edit as $value)
                        {
                        ?>
                        <form class="form-horizontal" id="addProduct" method="post" enctype="multipart/form-data">
                            <fieldset>
                                <legend>Edit Meal Policy</legend>

                                <div class="control-group">
                                    <label class="control-label" for="typeahead">Meal</label>
                                    <div class="controls">
                                        <input type="text" name="meal" id="text" class="span6" value="<?php echo $value['meal_type']?>" ><br />
                                    </div>
                                </div>

                                <div class="control-group">
                                    <label class="control-label" for="typeahead">From Time</label>
                                    <div class="controls">
                                        <input type="time" name="toTime" id="time2" class="span6" placeholder="" value="<?php echo $value['start_time']; ?>"><br />
                                    </div>
                                </div>
                                
                               <div class="control-group">
                                    <label class="control-label" for="typeahead">To Time</label>
                                    <div class="controls">
                                        <input type="time" name="toTime" id="time2" class="span6" placeholder="" value="<?php echo $value['stop_time']; ?>"><br />
                                    </div>
                                </div>
                                
                                <div class="form-actions">
                                    <button type="submit" name="submit" class="btn btn-primary">Save</button>
                                    <button type="reset" class="btn" id="cancel">Cancel</button>
                                </div>
                            </fieldset>
                        </form>
                        <?php
                        }
                        ?>

                    </div>
                </div>
            </div>
            <!-- /block -->


        </div>

    </div>

</div>
</div>
<script type="text/javascript">
    $("#cancel").click(function()
    {
        window.location.href= "<?php echo $this->basePath()?>/superAdmin/mealPolicy";
    });

</script>