<div class="block-content collapse in" style="overflow:visible;">
    <table class="table table-striped">
        <tbody>
            <tr>
                <th style="text-align:center;">Name</th>
                <th style="text-align:center;">Date</th>
                <th style="text-align:center;">Amount</th>
                <th style="text-align:center;">Action</th>
            </tr>
            <?php
            foreach ($data as $value)
            {
            ?>
            <tr>
                <td style="text-align:center;"><?php echo $value['employee_name']; ?></td>
                <td style="text-align:center;"><?php echo $value['month']; ?></td>
                <td style="text-align:center;"><?php echo $value['amount']; ?></td>
                <td style="text-align:center;">
                    <a href="/superAdmin/salaryAdvance/edit/<?php echo $value['id'];?>" ><img src="/images/edit.gif" border="0" width="40" height="40" id=""></a>
                    <a href="" ><img src="/images/delete.png" border="0" width="30" height="30" style="padding-left: 20px;" class ="del" id="del_<?php echo $value['id'];?>"></a>
                </td>
            </tr>
            <?php
            }
            ?>
            

           
        </tbody>
    </table>
</div>
