<script>
    $('#employeeName').live('click',function()
    {
        if(document.getElementById('employeeName').value == "selectOne"){
        alert('Select a name first');
        }
    });
</script>
<div class="span9" id="content">
    <div class="row-fluid">
        <a class="btn btn-primary " href="/superAdmin/salaryAdvance">Go Back</a>
    </div>


    <div class="row-fluid">
        <div class="span12">

            <!-- block - -->

            <div class="block">
                <div class="navbar navbar-inner block-header">
                    <div class="muted pull-left">Salary Advance Form</div>
                </div>
                <div class="block-content collapse in">
                    <div class="span12">
                        <form class="form-horizontal" id="addProduct" method="post" enctype="multipart/form-data">
                            <fieldset>
                                <legend></legend>

                                <div class="control-group">
                                    <label class="control-label" for="typeahead">Name</label>
                                    <div class="controls">
                                        <?php foreach($datas as $value2) { 
                                     ?>
                                
                                        <select name="employeeCode" id="employeeCode"> 
                                            <?php foreach($names as $value) {?>
                                            <option value="<?php echo $value['employee_code']; ?>" <?php if($value2['employee_code'] == $value['employee_code']) echo "selected";    ?>><?php    echo $value['employee_name']; ?></option>
                                            <?php } ?>
                                        </select>  
                                    </div>
                                </div>
                                
                                <div class="control-group">
                                    <label class="control-label" for="typeahead">Date</label>
                                    <div class="controls">
                                        <input type="date" name="date" id="date" class="span6" placeholder="" value="<?php echo $value2['month']; ?>" required><br />
                                    </div>
                                </div>
                                
                               <div class="control-group">
                                    <label class="control-label" for="typeahead">Amount</label>
                                    <div class="controls">
                                        <input type="number" name="amount" id="amount" class="span6" placeholder="" value="<?php echo $value2['amount']; ?>" required><br />
                                    </div>
                                </div>
                                <?php }?>                              
                                <div class="form-actions">
                                    <button type="submit" name="submit" class="btn btn-primary">Save</button>
                                    <button type="reset" class="btn" id="cancel">Cancel</button>
                                </div>
                            </fieldset>
                        </form>

                    </div>
                </div>
            </div>
            <!-- /block -->


        </div>

    </div>

</div>
</div>
<script type="text/javascript">
    $("#cancel").click(function()
    {
        window.location.href= "<?php echo $this->basePath()?>/superAdmin/salaryAdvance";
    });

</script>