<script type="text/javascript"> 
    $(document).ready(function() {
       
        showTable();
       

    });
    
    function showTable()
    {   
        
        $.ajax({

            type:"POST",
            url:"/superAdmin/salaryAdvance/ajaxList",
            cache:false,
            data:{},
            dataType:"html",
            success:function(data)
            {
                $("#ajx_table").html(data);
            }
        });
    }

       
    
    //Delete
    $('.del').live('click',function()
    { 
        var id= $(this).attr('id');
        var delId= id.split('_');
        $.ajax({
            type:"POST",
            url:"/superAdmin/salaryAdvance/delete",
            cache:false,
            data:{tableId:delId[1]},
            dataType:"html",
            success:function(data)
            {   alert(delId[1]);
                $("#msg").html(data);
                $('#msg').delay(2000).fadeOut();
                showTable();
            }
        });

    });

    
</script>


<style type="text/css">
     .del{ cursor: pointer;} 
</style>

<div class="span99" id="content">
    <div class="row-fluid">
      	<div class="navbar">
           	
        </div>
    </div>
    <div class="row-fluid">
        <div class="span12">
            <div class="row-fluid">
                    <a class="btn btn-primary" href="/superAdmin/salaryAdvance/listAll">List All</a>
                    <a href="/superAdmin/salaryAdvance/add"><button type="submit" class="btn btn-primary" style="margin-left:885px;">Add</button></a>

            </div>

            <div class="block">
                <div class="navbar navbar-inner block-header">
                    <div class="muted pull-left" style="text-align:center; float: left; width:100%;">Salary Advance<div id="msg" style="font-size:12px; color:red; text-align:center;">
                        <?php
                            if(count($flashMessages))
                            {
                                foreach ($flashMessages as $msg)
                                {
                                    echo $msg.'</blink><br>';   
                                }   
                            }
                        ?>
                    </div>

                    
                </div>
                    <div id="ajx_table"></div>
            </div>
        </div>
    </div>

