<div class="span99" id="content">
    <div class="row-fluid">
      	<div class="navbar">
           	
        </div>
    </div>
    <div class="row-fluid">
        <div class="span12">
            <div class="row-fluid">
                    <a class="btn btn-primary" href="/superAdmin/salaryAdvance/<?php echo $employee; ?>">List All</a>
                    <a href="/superAdmin/salaryAdvance/add"><button type="submit" class="btn btn-primary" style="margin-left:885px;">Add</button></a>

            </div>

            <div class="block">
                <div class="navbar navbar-inner block-header">
                    <div class="muted pull-left" style="text-align:center; float: left; width:100%;">Salary Advance<div id="msg" style="font-size:12px; color:red; text-align:center;">
                        <?php
                            if(count($flashMessages))
                            {
                                foreach ($flashMessages as $msg)
                                {
                                    echo $msg.'</blink><br>';   
                                }   
                            }
                        ?>
                    </div>

                    
                </div>
                    <div id="ajx_table">
<div class="block-content collapse in" style="overflow:visible;">
    <table class="table table-striped">
        <tbody>
            <tr>
                <th style="text-align:center;">Name</th>
                <th style="text-align:center;">Date</th>
                <th style="text-align:center;">Amount</th>
                <th style="text-align:center;">Action</th>
            </tr>
            <?php
            foreach ($data as $value)
            {
            ?>
            <tr>
                <!-- <td style="text-align:center;"><?php echo $value['employee_name']; ?></td> -->
                <td style="text-align:center;"><?php echo $value['id']; ?></td>
                <td style="text-align:center;"><?php echo $value['month']; ?></td>
                <td style="text-align:center;"><?php echo $value['amount']; ?></td>
                <td style="text-align:center;">
                    <a href="/superAdmin/salaryAdvance/edit/<?php echo $value['id'];?>" ><img src="/images/edit.gif" border="0" width="40" height="40" id=""></a>
                    <a href="" ><img src="/images/delete.png" border="0" width="30" height="30" style="padding-left: 20px;" class ="del" id="del_<?php echo $value['id'];?>"></a>
                </td>
            </tr>
            <?php
            }
            ?>
        </tbody>
    </table>
    <?php echo $this->paginationControl($this->data, 'Elastic', 'pagination.phtml');?>
     
</div>

</div>
            </div>
        </div>
    </div>




