<div class="span9" id="content">
    <div class="row-fluid">
        <a class="btn btn-primary " href="/superAdmin/leave">Go Back</a>
    </div>


    <div class="row-fluid">
        <div class="span12">

            <!-- block - -->

            <div class="block">
                <div class="navbar navbar-inner block-header">
                    <div class="muted pull-left">Leave Adding Form</div>
                </div>
                <div class="block-content collapse in">
                    <div class="span12">
                        <form class="form-horizontal" id="addProduct" method="post" enctype="multipart/form-data">
                            <fieldset>
                                <legend></legend>

                                <div class="control-group">
                                    <label class="control-label" for="typeahead">Leave Date</label>
                                    <div class="controls">
                                        <input type="text" name="date" id="date" class="span6" placeholder="dd/mm/yyy" required><br />
                                    </div>
                                </div>
                                
                                
                                <div class="control-group">
                                    <label class="control-label" for="typeahead">Leave Type</label>
                                    <div class="controls">
                                        <select name="leaveType" onchange='checkvalue(this.value)' id="leavetype" selected = "<?php echo $value['leave_type']; ?>">
                                    <option value="Full Day">Full Day</option>
                                    <option value="Half Day">Half Day</option>
                                        </select>
                                    </div>
                                </div>
                                
                                
                                <div class="control-group" style='display:none' id="fromTimeJ">
                                    <label class="control-label" for="typeahead">From Time</label>
                                    <div class="controls">
                                        <input type="time" name="fromTime" id="date" class="span6" placeholder=""><br />
                                    </div>
                                </div>
                                
                               <div class="control-group" style='display:none' id="toTimeJ">
                                    <label class="control-label" for="typeahead">To Time</label>
                                    <div class="controls">
                                        <input type="time" name="toTime" id="date" class="span6" placeholder="" ><br />
                                    </div>
                                </div>
                                
                                <div class="control-group">
                                    <label class="control-label" for="textarea2">Leave matter</label>
                                    <div class="controls">
                                        <textarea name="dis" id="dis" placeholder="Leave Discription" required></textarea>
                                    </div>
                                </div>
                                                                
                                <div class="form-actions">
                                    <button type="submit" name="submit" class="btn btn-primary">Save</button>
                                    <button type="reset" class="btn" id="cancel">Cancel</button>
                                </div>
                            </fieldset>
                        </form>

                    </div>
                </div>
            </div>
            <!-- /block -->


        </div>

    </div>

</div>
</div>