 <script type="text/javascript">
$(document).ready(function(){
    $("#skillnew").click(function(){
       var id=document.getElementById('noskill').value++;
       $("#result").before('<tr><td> Skill: <input name="skill'+id+'" type="text" ></tr>');
    });
    });
    
</script> 
<style type="text/css">
    .add { cursor: pointer;}

</style>
<div class="span9" id="content">
    <div class="row-fluid">
        <a class="btn btn-primary " href="/superAdmin/skill<?php echo $employee; ?>">Go Back</a>
    </div>

    
    <div class="row-fluid">
        <div class="span12">

            <!-- block - -->

            <div class="block">
                <div class="navbar navbar-inner block-header">
                    <div class="muted pull-left">Add Skill and Rating</div>
                </div>
                <div class="block-content collapse in">
                    <div class="span12">
                        <form class="form-horizontal" id="addProduct" method="post" enctype="multipart/form-data">
                            <fieldset>
                                <legend></legend>
                                
                               
                                

                <table>
                    <tr>
                        <td> Skill: <input name="skill1" type="text" ></td>
                       
                    </tr>
                    <div id="result"> </div>
                </table>
                                <div id="skillnew" style="float: left; padding-left: 10px;" class="add"><input name="skill"  id="skill" value="1" type="hidden" ></br>
                                    <image src="/images/add.png" height="40px" width="40px"/>Add More<input type="hidden" id="noskill" name="noskill" value="2"></div>

                             
                                
                                <div class="form-actions">
                                    <button type="submit" name="submit" class="btn btn-primary">Save</button>
                                    <button type="reset" class="btn" id="cancel">Cancel</button>
                                </div>
                                
                                
                                </fieldset>
                        </form>

                    </div>
                </div>
            </div>
            <!-- /block -->


        </div>

    </div>

</div>
</div>
<script type="text/javascript">
    $("#cancel").click(function()
    {
        window.location.href= "/superAdmin/skill";
    });

</script>
