<html>

    <table>
        <fieldset align="center">
            <legend><b>Home<img src="#" alt="Computer man" width="70" height="70"></b></legend>
            <div ><strong> 
                    <img src="/images/codex.jpg" alt="Computer man" width="700" height="200" align="center">
                    <h3 align="center"> Welcome to our home page</h3>
                    <tr><a href="superAdmin/registration"> <b>Registration </b>  <br> </a></tr>
                    <tr><a href=" superAdmin/registration/list "><b> Employee List<br></b></a></tr>
                </strong></div>

            </fiedset>
            </html>