<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"> 
    </head>
    <body>
        <form name="login" method="post" action="">
            <fieldset align="center" border="1">
                <legend><b>Employee List<img src="/images/profile.jpg" alt="Computer man" width="70" height="70"></b></legend>
                <table align="left" border="2"class="table table-striped">
                    <thead>
                        <tr>
                            <th>Employee Code</th>
                            <th>Employee Name </th>
                            <th>Department</th>
                            <th>Email ID </th>
                            <th>Contact Number</th>
                            <th>Date Of Joining </th>
                            <th>Monthly Salary</th> 
                            <th>Shift In Time</th>
                            <th>Shift Out Time</th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php
                        foreach ($datas as $key => $value) {
                            ?>                         
                            <tr>
                                <td><?php echo $value['employee_code']; ?></td>
                                <td><?php echo $value['employee_name']; ?></td>
                                <td> <?php echo $value['department']; ?></td>
                                <td> <?php echo $value['email_id']; ?></td>
                                <td> <?php echo $value['mobile_no1']; ?></td>
                                <td> <?php echo $value['doj']; ?></td>
                                <td> <?php echo $value['monthly_salary']; ?></td>
                                <td> <?php echo $value['shift_in_time']; ?></td>
                                <td> <?php echo $value['shift_out_time']; ?></td> <td> <a href="/superAdmin/registration/profile/<?php echo $value['employee_code']; ?>">View </a> <br><a href="/superAdmin/registration/edit/<?php echo $value['employee_code']; ?>">Edit</a> <a href="/superAdmin/registration/delete/<?php echo $value['employee_code']; ?>">Delete</a>   </td>
                            </tr>

    <?php
}
?>

                    </tbody> 

                </table>
            </fieldset>
        </form>
    </body>
</html>
