<html>
    <head>
        <link class="jsbin" href="http://ajax.googleapis.com/ajax/libs/jqueryui/1/themes/base/jquery-ui.css" rel="stylesheet" type="text/css" />
        <script class="jsbin" src="http://ajax.googleapis.com/ajax/libs/jquery/1/jquery.min.js"></script>
        <script class="jsbin" src="http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.0/jquery-ui.min.js"></script>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"> 


        <title>profile</title> 
    </head>
    <body>
	
        <form name="view" method="post" action="" enctype="multipart/form-data">
            <fieldset align="center"> 
              <?php foreach ($profile as $key => $value) { ?>
		
		<legend><b><h2 style="text-align: center;"><?php echo $value['employee_name']; ?> </h2> <img style="float: right;" src="/images/upload/<?php echo $value['image']; ?>" id="image" onmouseover="" width="100" height="130" border="6"  > </b></legend>
                    
                    <table align="center" border="0" cellpadding="4" cellspacing="4"> 



                        <?php //echo $id_proof= $value['id_proof']; exit;?>
                        <?php // echo $gender= $value['gender']; exit;?>
                        <b> <tr align="left">
                                <td >Employee Code</td> 
                                <td align="">
                                 :&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<?php echo $value['employee_code']; ?>
                                </td>
                            </tr>
                            <tr align="left">
                                <td>Employee Name  </td> 
                                <td align="">
                                    :&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<?php echo $value['employee_name']; ?>
                                </td>
                            </tr>
                            <tr align="left">
                                <td>Employee Last Name </td> 
                                <td align=""> 
                                    :&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<?php echo $value['last_name']; ?>
                                </td>
                            </tr>
                            <tr align="left">
                                <td>Date Of Birth : </td> 
                                <td align="">
                                    :&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<?php echo $value['dob']; ?>
                                </td>
                            </tr>
                            <tr align="left">
                                <td>
                                    Gender
                                </td>
                                <td align=""  >
                                  : &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<?php $gender = $value['gender']; ?>
                                  
                                </td>
                            </tr>
                            <tr align="left">
                                <td>Email ID  </td>
                                <td align="">
                                    :&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<?php echo $value['email_id']; ?>
                                </td>
                            </tr>
                            <tr align="left">
                                <td>Contact Address </td> 
                                <td align=""> 
                                    :&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<?php echo $value['address']; ?>
                                </td>
                            </tr>
                            <tr align="left">
                                <td>Emergency Contact Number</td> 
                                <td align=""> 
                                   :&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<?php echo $value['mobile_no1']; ?>
                                </td>
                            </tr>
                            <tr align="right">
                                <td></td>
                                <td align="left">
                                    :&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<?php echo $value['mobile_no2']; ?>
                                </td>
                            </tr>
                            <tr align="right">
                                <td></td> 
                                <td align="left">
                              :&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<?php echo $value['mobile_no3']; ?>
                                </td>
                            </tr>
                            <tr align="left">
                                <td> Date Of Joining  </td>
                                <td align="">
                                   : &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<?php echo $value['doj']; ?>
                                </td>
                            </tr>
                            <tr align="left">
                                <td>Department  </td>
                                <td align="">
                                       :&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <?php echo $value['department']; ?>
                                        
                                </td>
                            </tr>

                            <tr align="left">
                                <td>Designation </td>
                                <td align=""> 
                                        
                                       
                                        : &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<?php echo $value['designation']; ?>
                                  </td>
                            </tr>

                            <tr align="left">
                                <td>Monthly Salary </td> 
                                <td align="">
                                   :&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<?php echo $value['monthly_salary']; ?>
                                </td>
                            </tr>
                                   
                            <tr align="left">
                                <td>Device Code  </td> 
                                <td align="">
                                   : &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<?php echo $value['device_code']; ?>
                                </td>
                            </tr>
                            <tr align="left">
                                <td>Company Name </td> 
                                <td align="">
				    :&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<?php echo $value['company']; ?>
                                </td>
                            </tr>
                            <tr align="left">
                                <td>Company Location  </td>
                                <td align=""> :&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<?php echo $value['location']; ?>
                                </td>
                            </tr>
                            <tr align="left">
                                <td>Employee Grade </td>
                                <td align=""> 
                                    :&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<?php echo $value['grade']; ?>
                                </td>
                            </tr>
                            <tr align="left">
                                <td>Employee Team</td>
                                <td align=""> 
                                    :&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<?php echo $value['team']; ?>
                                </td>
				
                            </tr>
                            <tr align="left">
                                <td>Employee In Time</td>
                                <td align=""> 
                                    :&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<?php echo $value['intime']; ?>
                                </td>
                            </tr>
                            <tr align="left">
                                <td>Employee Out Time</td>
                                <td align=""> 
                                    :&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<?php echo $value['outtime']; ?>
                                </td>
                            </tr>
                            <tr align="left">
                                <td>Employee Category  </td> 
                                <td align="">
				    :&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<?php echo $value['category']; ?>
                                </td>
                            </tr>
                            <tr align="left">
                                <td>Employment Type  </td> 
                                <td align="">
                                    :&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<?php echo $value['employment_type']; ?>
                                </td>
                            </tr>
                            <tr align="left">
                                <td>Date Of Completion </td> 
                                <td align="">
                                    :&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<?php echo $value['doc']; ?>
                                </td>
                            </tr>
                            <tr align="left">
                                <td>Card Number </td> 
                                <td align="">
                                   : &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<?php echo $value['card_number']; ?>
				    
                                </td>
                            </tr>
                            <tr align="left">
                                <td>ID Card Number </td>
                                <td align="left"> 
                                    :&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<?php echo $value['id_card']; ?>
                                </td>
                                <td align="left">
                                   <img src="/images/upload/<?php echo $value['id_card_image']; ?>" width="70" height="90" border="0">
                                                              
                                </td>
                            </tr>
                            <tr align="left">
                                <td>Passport Number </td>
                                <td align="left"> 
                                   :&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <?php echo $value['passport']; ?>
                                <td align="left">
                                    <img src="/images/upload/<?php echo $value['passport_image']; ?>" width="70" height="90" border="0">
                                    
                                </td>
                            </tr>
                            <tr align="left">
                                <td>Aadhar Number </td>
                                <td align="left"> :&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<?php echo $value['aadhar']; ?>
                                <td align="left">
                                    <img src="/images/upload/<?php echo $value['aadhar_image']; ?>" width="70" height="90" border="0">
                                    
                                </td>
                            </tr>
                            <tr align="left">
                                <td>Driving License Number </td>
                                <td align="left"> 
                                    :&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<?php echo $value['driver_license']; ?>
                                <td align="left">
                                    <img src="/images/upload/<?php echo $value['driver_license_image']; ?>" width="70" height="90" border="0">
                                    
                                </td>
                            </tr>
                            <tr align="left">
                                <td>Employee Feedback</td>
                                <td align="left">
                                    
                                        :&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<?php echo $value['feedback']; ?>
                                  
                                </td>
                            </tr>
                       <?php } ?>
                </table>
            </fieldset>

        </form>
    </body>


</head>
</html>
