<div class="span9" id="content">
    <div class="row-fluid">
        <a class="btn btn-primary " href="/superAdmin/user">User Listings</a>
    </div>


    <div class="row-fluid">
        <div class="span12">

            <!-- block - -->

            <div class="block">
                <div class="navbar navbar-inner block-header">
                    <div class="muted pull-left">User Adding Form</div>
                </div>
                <div class="block-content collapse in">
                    <div class="span12">
                        <?php 
                        foreach ($edit as $value)
                        {
                        ?>
                        <form class="form-horizontal" id="addProduct" method="post" enctype="multipart/form-data">
                            <fieldset>
                                <legend>New User</legend>

                                <div class="control-group">
                                    <label class="control-label" for="typeahead">Username</label>
                                    <div class="controls">
                                        <input type="text" name="username" id="username" class="span6" value="<?php echo $value['username']?>" placeholder="Username" required><br />
                                    </div>
                                </div>

                                <div class="control-group">
                                    <label class="control-label" for="textarea2">Password</label>
                                    <div class="controls">
                                        <input type="text" name="password" id="password" placeholder="Password">
                                    </div>
                                    <span style=" margin-left: 180px; color:red;font-size: 10px;">If you want to change Password please enter new Password; else dont type anything inside this text box</span>
                                </div>
                                <div class="control-group">
                                    <label class="control-label" for="textarea2">User Type</label>
                                    <div class="controls">
                                        <select id="userType" name="userType" required>
                                            <option value="">User please</option>
                                            <option value="admin" <?php if($value['user_type'] == 'admin') echo "selected";?>>admin</option>
                                            <option value="user" <?php if($value['user_type'] == 'user') echo "selected";?>>user</option>
                                            <option value="superadmin" <?php if($value['user_type'] == 'superadmin') echo "selected";?>>superadmin</option>
                                        </select>                                    
                                    </div>
                                </div>
                                
                                <div class="form-actions">
                                    <button type="submit" name="submit" class="btn btn-primary">Save</button>
                                    <button type="reset" class="btn" id="cancel">Cancel</button>
                                </div>
                            </fieldset>
                        </form>
                        <?php
                        }
                        ?>

                    </div>
                </div>
            </div>
            <!-- /block -->


        </div>

    </div>

</div>
</div>
<script type="text/javascript">
    $("#cancel").click(function()
    {
        window.location.href= "<?php echo $this->basePath()?>/superAdmin/user";
    });

</script>